apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: calcom-cluster
  namespace: calcom  # The namespace where you want your database
spec:
  instances: 1
  primaryUpdateStrategy: unsupervised
  storage:
    size: 5Gi
