apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: chatui
spec:
  project: default
  sources:
    # --- SOURCE 1: The Helm Chart from Git ---
  - repoURL: 'https://github.com/cjbarroso/nexoflow-k8s-apps.git'
    path: apps/chatui # This tells Argo CD where the chart is
    targetRevision: master # The branch, tag, or commit in Git
    helm:
      valueFiles:
        - $values/apps/chatui/chatui-values-production.yaml

    # --- SOURCE 2: The values files ---
  - repoURL: 'https://github.com/cjbarroso/nexoflow-k8s-apps.git'
    ref: values

  destination:
    server: 'https://kubernetes.default.svc'
    namespace: 'chatui'
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true