---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: caldiy-db-backup-creds
  namespace: caldiy
spec:
  encryptedData:
    accessKeyId: AgAqxh21aR3jHLYJvAQVBmBHImLIU1USBq/J2RCjhjeSIs14Iu4TcYEHbjFcqBKlhOXFaUZc5leeF0kNJoyhqVYPegLPuO0LBGa0z6vs04gD+6sPVmRynVlLSy3NHHQRTLmHKXEFU96iFRVyjoJj1Ug2h6cXfiuasPeZ0lWbbexa2xrmCdUSdIBVStG9FpoML0y1+5E2bcsOJD0yz/g1mqC/O0HgRrKjB/Mgljk19wZBsbM8lVZopJfxejZO57f0E4SH2pKQKBSCxapHC7XDoWYorvcgbvte1TCD2Lvlmy9hPY2lxx8+dVEUytEOBzHrsrVLenLnTHt98CdwhppEfH83Rvwwj6zp1mi9LW03yS8j8GFu6awYDh6Eg5TS0eS6JBhM2ZEn3bKuRKUbfRzQ/BlP0v7iWCkqthiB9k+zq234ZS6r2/fFt+RIUNn1oIETwzmqp+l9Y0yDvGKHYQKnZ9jBlxO1xKL4KQWkSNna1E+ggPw8vTkyDtdgEgZXuLbHuc/8n+FfjzNrBirf3xD4Z/TG5J+U2bRSOzbkfBKc+MevGKx15TcCwVqmGhx0WDc0NknAUJ+6e1ejlhBFkinJRWAoCHovfha4Xwu3dIaSWv5NPuX9GYi9AyA5fLxDnWRqADxYDilLcs5d6ka/MPqe4XqLyRKMhGEcIyPyVouCeoFV3inKmCP1kU8BYvyTCovxC0g5Cuhf4A7+XXD133u0/qxFEgV1+90Xys3kcmiJbEZvqg==
    secretAccessKey: AgCkcJGV1r6tkn0G+pnL72qbOoxIfP0GIYPLbhah8GFeM4BuN2m+cO+BJGTpOsvqEUP/zPYIoRmjo5wa1m65WfIp7h6sG5YdfyZFvAFamNEyIWAkUw5YgQlrJuQ0TSQS5kBrbOj7qLvGcjlApNLoIarYYSf+o3P1+XbHkTIg2g+wwk3Dqv6CWlstJuyZmorRw5Rc2l5OMRNFo8hH3BwOTfcGDYru89WAVnWxxfbGiUuVdIqvEM74vl4WWBEcNb+J7o7ijBiMUCaHMp52nJt6d6bkYbUAiVPylJVwCF38Q2udB4lc5ylZuXh7WpLRLmoDOKuthoJtRDn4LqTAO2wIjLnnQGScFOFycsRvwrZ0BFLnKSXyTRRekWfPqdScR6I6e0UwBQmZEFVxlZgchhOdX4xe8dRoAtblH8m8KGJqXYDSLkiLGQP+h/9DS0dNjabsdp4JTIRzgkap13EjhRn1hq9U5wa4UT0BhhQTBOUKBqD87Dst0X2cai/f3g1SuNUc62tnxPmVmTI98J6yPYkxszDHrfD3+cSImkBoDMWWvKPWwilze6pJod/DfTag62M5QJgqOXuFhr8AIQf0xa87xqxoirFf8cYVvelMwafg8AG80NevCspjd2bAcJuS35BzggeheF1BPpQY6eneAze52qm1GAHmYNNhfZ4swHJ+APO4WE7ppSLepUfe7EJnWsym8vOF+TMactJOQj2QZ2bB2wQ4FCMVcX1eXO3Dao//5FWYrkZHH2/msiBvPugM31X6ps1KbcCC4T7kVeG3QlZ74YY2
  template:
    metadata:
      name: caldiy-db-backup-creds
      namespace: caldiy
    type: Opaque
