apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: waha
  namespace: argocd # This should be your Argo CD namespace
spec:
  project: default # Change this to your desired Argo CD project

  # Source of the application's configuration
  # This points to the Helm chart in the same Git repository.
  source:
    repoURL: 'ssh://192.168.1.10:23231/nexoflow-k8s-apps'
    path: apps/waha # EDIT THIS: Change to the path of your 'waha' chart directory
    targetRevision: HEAD # Or a specific branch/tag

  # Destination where the application will be deployed
  destination:
    server: https://kubernetes.default.svc
    namespace: waha # The namespace where you want to deploy WAHA

  # Sync policy
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true # Automatically create the namespace if it doesn't exist
