apiVersion: v2
name: waha
description: A Helm chart for deploying the WAHA - WhatsApp HTTP API.
type: application
version: 0.1.0
appVersion: "latest"
keywords:
  - waha
  - whatsapp
  - api
home: https://waha.devlike.pro/
sources:
  - https://github.com/devlikeapro/waha
