apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: valkey
spec:
  project: default
  sources:
  - repoURL: 'https://github.com/valkey-io/valkey-helm'
    targetRevision: 'v0.8.1'
    path: valkey
    helm:
      valueFiles:
      - $values/apps/waha/waha-valkey-values-production.yaml
  - repoURL: 'ssh://192.168.5.80:23231/nexoflow-k8s-apps'
    targetRevision: HEAD
    ref: values
  destination:
    server: 'https://kubernetes.default.svc' # Deploy to the local cluster
    namespace: 'waha'
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
