{{- if and .Values.persistence.sessions.enabled (not .Values.persistence.sessions.existingClaim) }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ printf "%s-sessions" (include "waha.fullname" .) }}
  labels:
    {{- include "waha.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.persistence.sessions.size }}
  {{- if .Values.persistence.sessions.storageClassName }}
  storageClassName: {{ .Values.persistence.sessions.storageClassName }}
  {{- end }}
---
{{- end }}
{{- if and .Values.persistence.media.enabled (not .Values.persistence.media.existingClaim) }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ printf "%s-media" (include "waha.fullname" .) }}
  labels:
    {{- include "waha.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.persistence.media.size }}
  {{- if .Values.persistence.media.storageClassName }}
  storageClassName: {{ .Values.persistence.media.storageClassName }}
  {{- end }}
{{- end }}
