apiVersion: v1
kind: Secret
metadata:
  name: {{ include "waha.fullname" . }}
  labels:
    {{- include "waha.labels" . | nindent 4 }}
type: Opaque
{{- $hasSecret := or
    .Values.config.security.apiKey
    .Values.config.security.dashboard.password
    .Values.config.security.swagger.password
    .Values.config.advanced.proxy.password
    .Values.config.sessionStorage.postgresqlUrl
    .Values.config.sessionStorage.mongodbUrl
    (and (eq .Values.config.mediaStorage.type "S3") .Values.config.mediaStorage.s3.enabled)
}}
{{- if $hasSecret }}
stringData:
  WAHA_API_KEY: {{ .Values.config.security.apiKey | quote }}
  WAHA_DASHBOARD_PASSWORD: {{ .Values.config.security.dashboard.password | quote }}
  WHATSAPP_SWAGGER_PASSWORD: {{ .Values.config.security.swagger.password | quote }}
  {{- if .Values.config.advanced.proxy.password }}
  WHATSAPP_PROXY_SERVER_PASSWORD: {{ .Values.config.advanced.proxy.password | quote }}
  {{- end }}
  {{- if .Values.config.sessionStorage.postgresqlUrl }}
  WHATSAPP_SESSIONS_POSTGRESQL_URL: {{ .Values.config.sessionStorage.postgresqlUrl | quote }}
  {{- end }}
  {{- if .Values.config.sessionStorage.mongodbUrl }}
  WHATSAPP_SESSIONS_MONGO_URL: {{ .Values.config.sessionStorage.mongodbUrl | quote }}
  {{- end }}
  {{- if and (eq .Values.config.mediaStorage.type "S3") .Values.config.mediaStorage.s3.enabled }}
  WAHA_S3_SECRET_ACCESS_KEY: {{ .Values.config.mediaStorage.s3.secretAccessKey | quote }}
  {{- end }}
{{- end }}
