---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: hhccia-core-db-app
  namespace: hhccia-v2
spec:
  encryptedData:
    password: AgBN0IhG4VCtig3YAPvNX8lFqQfrW4EjO5WrXUb3k/4b/gV20D9qRCt1tAN9WjU4n3ovEnaLwelceexE61AU6SfCS5CUqADBQFSgxLoIdixatasyAo6KSmi03jXyhIdbgi9qgy5GpweZjvnYoEz9zJXmUzNLl0xBz1meX4epOVXiU7aaMfud5Qyb6Lp1Y8Xs7ZIMdtZ07MV6TDAgmxJdCAY0WZ8YOaQn+1ixf0IbJIsNIp6YKAxyb528nb0UDU59v7XiDdeydWe6bWlt7dsG+B6Bn/FYk+bmDnwubY6OlPCP1Ml9g8bU+j4+AmObKVRwP512RxKq3GHfC4LKMGSh+17fcgpdLoDd5maikept+6IUHXTWOeiK1UoHi6BwsZ2N+bGBJeCz7P8ogOjgMDS5vF3e4BFwtsAIy57l945QisaXmoYsj/qLGiaklWa20UpxRa98hWbwRMhbUZlTOIOXIp7g8SWEQdqfGngPuo7ezTrLc5tuVQQbw1IGnJOoWb4wzs8/IOataZuRtBqJt0XCdCmPDSRkfLruqqiKHohdiqB6KXyIPwMK0h/O2V0un2JK0rPE5Qm4PuSmgX4c7Byf/KE5FAnHjiV9Qq7zP173KgoUhlGO+7QT2UJPXwszNJ3byTHEOyAititytVH3YgmTqAMHbvX+BmGdvoJ7o1VShn665IQ357yp6NkyWNQXK4UlsCsVXFcyyycE41LhlvGXwjfMAGzwlQ/EFxE=
    username: AgBKbB27zKGPpk5ce32FykNvHjq7wrNBoaRbjgDVv+B5yCRVZn4Ekw7lsTPSdI5aJRoxXE/Yiy/l7w0apIb7e+leVSev9g65dR4DQcKHb0q204ZuHZ3LIyISsuhEvAbq4PaACopPBX9lJsjWRh/U4bJQgySb3fwbOXTevJt8XxhEmR1cStogP16Q8cVHbpyWxLdZgNSM2aJ11W7YnlhHQAtOSY/eq9cmY2+glk1ghlnHyWJYSgTdKdly4OZAYjdEjXVpbIGU+hIMkFA9O2AYb8Rrf441u63CWh0SpI0p3fq5x2kgGJ5sxPX6SztaRm1Yi3mJuWggGvRv/NtFxCjbK7ZblNWLE8YfsibauW5m/lV8odbS7o6CiufuCz/YSZluf2ebkodZCUNxR8tyWgZSmOHqiHHfZWvPKjZHZ2dIDgh+KDrSENF2YawgwLOagSfdxyPaBrIPE0F6nl+GBBI3tu7LEKWJ7PYyhh35scWRNGwfS8bkH/tWTCP8CZeH0/keZf5dizYmZRQqOg5iRbhyE+Yv5aEUoTrRigZ3/qtSfDVHXCPGw3mxqK/90TmqW2FfRlqXs3TrfbpvYHvG+Cm4nRYapg/WEl8BsXC3bf/gUKLbs3GuePipO/O/xcBTmechv3VMBcDZTWrdBl7R5iLc5chHJ04Ttuvpok6fE2jdTWWGHh9kXuGlvoohjSJpWucEdujU/RJUYMw=
  template:
    metadata:
      name: hhccia-core-db-app
      namespace: hhccia-v2
    type: kubernetes.io/basic-auth
