---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cwa-gmail
  namespace: calibre-web-automated
spec:
  encryptedData:
    gmail.json: AgC5bi/0Hg5IC2mthVQtFo4AVts4MnfvZlsZ4PA4vkRNAXrEamnyOlWmYDC1G5dAnSt34tZe1cmCztbc43Seby6SCzivinAOz6bKjy57K7NkQToiNF9/TZ0q4SOMx2xGIo1Y5zJXOI8h2rrPoGpC/mTPkTCVGxOeCNXvsrXv/9y7AkUkFBgD0lp+zCvoOjDtp+I3d8V+G58d6xZEGu8XD9cYS57yI9qEjdMEM9TpGahcQF8sYSp2zz0Rg//FUJmqWUId1A3eZePDyXqf6huZygSXG202HOesqw+Td+FdTwYInQxvK4FeE3QWVUeoTeELugiKLytdjopTSpRSHpEqadjt6eAFNJkkQN+jA7Etsy78A1vjhFQNsIpLzl5MCjGo51A/ea0R0rtcRbHmAuPZjqcutsTlLQUYyoKS3nbJym751p9oZ7zKmd3QH9HpYGpeRAxCjWluDF+SzqX2bprYHQWx88jQUhlucwDQkWzCHKV35oOoCgv9qV6asknXHF3YTxw+XLwje9Kv9b5KJwo0IZgvYj1bPX8kZ2RTNfOfGTlT4n1w12xwrbS+1J8G1r1khJ6m/NGVArTvzLmx4xD9IqVo/VH8BzRkQmJnHRXC6G1bo0S2nwE9v4zKN3X5o73vIhQw9vLPbmQY7l693NDkMKMncW4zjabNJRbFj/v+YSNywYssw4zJvn2vo5evLt5vRMOLbeVoWRb1v/n/m2Sovy+M7iY4FyTSVlvi+K2xCKEZxG/AMlFyKQAvstt6l+0iMlsw+aGcLlYfT0yoC3UmQmbrjd3nq7hN9lzpwKz7Z6jKULsw38SjA0NZyipYZ8iLwKPFcPvkT4uo5Tsujb4S88dfPSYqv9LVGWjAF05g53ObfZqZySPqOHdhIMiqEQBqK4dqQp8PWmgY8HKHLug+vPOFLTNGjNhdPkAifm7Z3CnzPqd4zY91J4pj5PM3irQjY7QIc0RHNQAOjK+UVygAbs+XmqxRwcvf+LRnmv2Im28Gf06Jgp8JMhDop81o+8Y1I0/6ED/5M9/5QOiWceMeYk8h0aq88cBD7MDGVxGH/biPKa6UW5pLxv1uI5PX+YpmNUADB9EYvSO3yowKt0F226nTCIId745YOs5kyF79fCDYv9EdFeEZYIHWw/+hc9ddO1auD/kgrmPIS2YskjnyIsvXkVnD/e9r3p6JsiKf+skJhz0V+ZiGG+SaHq6Mjif4FU3mcr0580xD94nDzPM/T9ae0ocsqI4dQLyO7BlJu8FYsQ01
  template:
    metadata:
      name: cwa-gmail
      namespace: calibre-web-automated
    type: Opaque
