apiVersion: v1
kind: Service
metadata:
  name: calibre-web-automated
  namespace: calibre-web-automated
spec:
  type: ClusterIP
  selector:
    app: calibre-web-automated
  ports:
    - name: web
      protocol: TCP
      port: 8083
      targetPort: web
