apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
spec:
  project: support
  sources:
    - repoURL: https://charts.jetstack.io
      chart: cert-manager
      targetRevision: "1.20.2"
      helm:
        valueFiles:
          - $values/apps/cert-manager/cert-manager-values.yaml
    - repoURL: https://github.com/cjbarroso/nexoflow-k8s-apps.git
      targetRevision: master
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: cert-manager
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
