#small deployment with nodeport for local testing or small deployments
main:
  persistence:
    enabled: true
    type: existing
    existingClaim: n8n-data
    accessModes:
      - ReadWriteOnce
  config:
    n8n:
      n8n_enforce_settings_file_permissions: true
      # encryption_key: Zf8lB4nL1E+gWWRC5RjkKLaXGm1FzOxF
      hide_usage_page: true
      host: flow.cjbarroso.com
      protocol: https
      node_env: development
      webhook_url: https://flow.cjbarroso.com
      runners_enabled: true
      redis_host: redis
      redis_port: 6379
      queue_health_check_active: true
      db_type: postgresdb

  extraEnv:
    DB_POSTGRESDB_HOST:
      valueFrom:
        secretKeyRef:
          name: nexoflow-cluster-app
          key: host
    DB_POSTGRESDB_PORT:
      valueFrom:
        secretKeyRef:
          name: nexoflow-cluster-app
          key: port
    DB_POSTGRESDB_DATABASE:
      valueFrom:
        secretKeyRef:
          name: nexoflow-cluster-app
          key: dbname
    DB_POSTGRESDB_USER:
      valueFrom:
        secretKeyRef:
          name: nexoflow-cluster-app
          key: user
    DB_POSTGRESDB_PASSWORD:
      valueFrom:
        secretKeyRef:
          name: nexoflow-cluster-app
          key: password

