apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: nexoflow-cluster-daily
  namespace: nexoflow
spec:
  schedule: "45 1 * * *"
  cluster:
    name: nexoflow-cluster
  method: plugin
  pluginConfiguration:
    name: barman-cloud.cloudnative-pg.io
  backupOwnerReference: none