apiVersion: barmancloud.cnpg.io/v1
kind: ObjectStore
metadata:
  name: nexoflow-object-store
  namespace: nexoflow
spec:
  configuration:
    destinationPath: s3://backups-k8s/nexoflow-cluster
    endpointURL: https://77df3d66af9eb572fe180d800d44127b.r2.cloudflarestorage.com
    s3Credentials:
      accessKeyId:
        name: backup-creds-secret
        key: accessKeyId
      secretAccessKey:
        name: backup-creds-secret
        key: secretAccessKey
    wal:
      compression: gzip
    data:
      compression: gzip
