apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nexoflow
spec:
  project: default
  sources:
  - chart: n8n
    repoURL: registry-1.docker.io/bitnamicharts
    targetRevision: 1.0.0
    helm:
      valueFiles:
      - $values/apps/nexoflow/redis-values-production.yaml
  - repoURL: 'ssh://192.168.1.101:23231/nexoflow-k8s-apps'
    targetRevision: HEAD
    ref: values
  destination:
    server: 'https://kubernetes.default.svc' # Deploy to the local cluster
    namespace: 'nexoflow' 
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
