apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: nexoflow-cluster
  namespace: nexoflow  # The namespace where you want your database
spec:
  logLevel: info
  instances: 1
  primaryUpdateStrategy: unsupervised
  enableSuperuserAccess: true
  inheritedMetadata:
    annotations:
      # Excludes the main database volume from Velero's File System Backup
      backup.velero.io/backup-volumes-excludes: pgdata
  plugins: 
  - name: barman-cloud.cloudnative-pg.io
    isWALArchiver: true
    parameters:
      barmanObjectName: nexoflow-object-store
  storage:
    size: 10Gi
