---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: authentik-db-app
  namespace: authentik
spec:
  encryptedData:
    password: AgBxfKqt+0PG+1B7FWvRTvTs7wwQGUOI9oYAXob1aTBX/WVmxNzJ1Tt235LQiUudiDrpwNmBZo6XAnIcUmybyjeSPoQN3GmjiKbcc9EwAXixFnruVzEXPX/HT6iGqnySEruviCdure1sN3ydYQQG8ocdEpCGrMELWGJ9+TeUPJ0UccuDsOcM1NUJS8NivkV/w4L+wxG2WwqrtdmpmeCf5+hx/h84gqPi9pd0o6j1Sb8UJn0LlkbE8XQTC/Gpb1b+eqfvu7kucJNyVGruQPgWsOaMNYOqF7SIp25j4V9uLNKqew8kC5g5RcF2bOvxWhQ1SGSllc5U1c5gImtiNykg4KI+b/qgox8NNzFAMzsqjlYoNlG9NU52bZ1J5tRk8vKhKVRZ59TUjo08diRiZQ8qeXUX7O2oqerTZnSeataYaKhN3wF0VmEi3zTpAVwbpbQl9imIXhaqjfjMAfdTNGgo3dpTCXbB1EUn8AEGHyjYPW7TBElDHlAGth0shGGO60HREPRNZRjouRGQmoPq5HjsMPBQgw5X2qQH/28r2yMZp0kkzG9g9di48UDHxm6V4bd9P1KxVgeRfzGjh4XcWMhpPH6sztKuoJD9Yh9Xk4XUqboF0eGf8g/c4KPEvyCeveWhFkiRHLwGwx56BPXSkb1bT+38Q6Nqmd/qMH3Uw9i3yONnEZc6gKS9uwzQThu2ZXJl1wbCOFLwJJ6dycxjpSQ2/MJzxLeABbpLvqk=
    username: AgCLX9ltHDoLlJghRri5rGzKM1MUr/SUX26IYmFL+YUeKdPCK+EKCEa9ix0OEuPWPZghuu5xgb7ULZuLmtm5J0IEHS/1hQbZUp4GOyue6IkbiOuPPRSC60aL9OmafH0r7UxDfW0OtkWWvN7ubfw+jAk9D4Swx8xRv2qZKuzN7iFsw1xOE3uhYYu4J6I1pF+rz0rOrbTRZsKDsPWsDMfUo821H3q/rXPIdC40QVJsS7nvmOuyQH6vvetgRnc0yWr/JmGU8XFFElwzGOSW/PMpi6QAR4c2r7jN6q9TMlxihS6UqW5gR1AgNRoqF9uGda2njiguRWCc2kni/CnPsMA3tl/aWWxeo0L5c62WUOIhicnMFG/Fs8+6bCE3msI6r97cXL31bfLtzsvNWykiU+cTm42B6oqDRibJxGidlGwwRE2Mfetu2M7leaJsvR/irxGGUwPSFquYHKnXiuDrl/aT17ZsdQ6ijbllslQ7K+B8UO92j88dzAARpt8S+bj97VpC5umBCdumoMj/Tt0BbLT3kbcR/XA3QzUMnvkYOBPedQF9CYcMahklQt++ahxCp5CBs4QC7nKtZuekYJ8Y694vpMM8CMZQ/hNVKmNpoAb6nByEE8rAXVM91EYL1bD3NU+75/8G8a1+GwSg7dBnhK8Lzwn32R1t899r2q0RXHkzsrQHWCO6/8yMXP08W4G2HfERc/Tr7xjpyWgNZls=
  template:
    metadata:
      name: authentik-db-app
      namespace: authentik
    type: kubernetes.io/basic-auth
