---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: hermes-secrets
  namespace: hermes
spec:
  encryptedData:
    OPENAI_API_KEY: AgCh+FRj2ni9jLOYYr+U9Izv1bbcjd2uoOhaV2jzwKVao33+i96twOQyf6hcbchgtwUS5m/C5nmF7TiDf/gyVa7tZqZWy14Vybz8BhCG4If7aSOk2la2okHSo74pvxIxahb2y2maEB7lLgTk5jPpPGzoe3jamFrZtTsdxPFWXv9inQqXKSsW1N2QybvzGNZdlsudjVb9w/lF/D7tIk9uR7/MukBEqrXUOYX6AvK9PBbqaT5fNK97+fVGdncE4A0sTbuY/ixVrtKFmitzN5twj7W/CmDwAgMAnrtFSXJe4HUQByrCiq5U1OvSRqMgCBN5wk2J20lPWjCSTaopQ2qsAcHykSy5iWQlIUWjYGyA4ZGAhH5QLNP5PxZ+/h8vkgiKcICxSja1uWLU53t2D/txZEkVoBBXhhx4g1a23+XZOp1qzejcYjrmgLxL+JD8nXPvMivbcm8NNQAZJ6VR9EzU+wEx11gTuUaBRY1s8h8Q2xSgryhZu0+ead5G7dXIkarWdh0Cmrhv1hjFSngqdTFRx8gFfelb+7jZZrlCeYBeBAqhCZjV2UDftCi/Q3D3N8ls/Wn20ih0GgUDS+D17x0ImvI5sTFC18uvQ3kcxfsVAv7hWjFTgbfCIIjENkETmX/XFYNq8/c+1x6BWAD1oF8uJquZD1rtIL5UitE3P8+rWhDT4T94kbw8UrDRwdxw7pLkryI=
  template:
    metadata:
      name: hermes-secrets
      namespace: hermes
