---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: planka-secretkey
  namespace: planka
spec:
  encryptedData:
    key: AgBwvNjhBIA0eUtr7McjMONSOZTH4p+PKUBkO/tAT5Ja5SVdiIIwccH0MI2KYbO3m/KnNd/btbcc4e8neZJfQyH/wRFfLiYBB7i7Xe8/mSF4Z3j6Zo61JmF1YPMXMk966mmP15toF1xcLy8cINAo2SOFxXKp7U8mebzdFEYFgR+nlDZXyD0MIliObL6kx+Af3S74lS7/CVyBeTtKyAiy73JzhvRfUVnsRco1/4HhsLhFXOBF9uoWKEHaQnHWBwd0R2bpsTwojrMpjd7GfJwYgQkEx4RdBinsMfpt+YKbOgA17wUHRd4t9s6wz9f1V29cCNRNB0zy4UAw0daf/bavj/U2rwV1fyk+JFMD4nKFFEzqtolGAr9QcQuMPMR0Cw0YhQRWE2fDACh5uODSJ+fidgOdncHqf3wy3KJt36bgBnrQfUkHq4WdIFhqyskrTXjPZBZf1sIz4kfwqJlms7oZStRaOF+sDDIOoKsqIz4Y49j5JfwLzb4kxDxSRmQsfJqLAC43CQXrXN8kLLqodgaRnqsfWiJCJv0ifpIKrO5x1ji6/veDYwehdilBE9O1vyT8qPbsshhxPDZYiaLJsOqKxYIuF7EZg6ZvPwC90QGGFwf4Z9TKekgHOR7J2xdCtcggS/h70x0oErJv/GRWwanD2TC46lI4GHfwL7x8n3zayWtr2F1CnKdIN6ce5yIFdP3VV/K9G03jaH3GjJoZV3fnpv0TZ91Sa4tLJ+uvqZttpZzjwgMIkecomWY2TKivpeHQoRdu9FQJt535YQeYvkRxWPWFQTEWgHBsicH0DAO2il3SCBKN1jCJemnuXh1DGWd5YS3cE7U2JldJxOq21uAZWUdfDzMeGOlm1lPtyRIeApJUXg==
  template:
    metadata:
      name: planka-secretkey
      namespace: planka
