---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: planka-admin
  namespace: planka
spec:
  encryptedData:
    password: AgBdwzP9X1vJm7haBB0Nk6slbaGtpR2GqqnomKWamM+2hEY5w9JE6493mYWL7tXLeKp9c7fO8U8tzhuPK1KA6/S2fvEObFb650Y4OfXw8F5Y6ZQmHmGxZyI0CmyQwW75kwW4qaeiqJzJG990Myah2H5bsmUh4PtiDeTFQeFdKf0xMm4Ya6CveTXwU/6NMXOVZHM0/U6ipvz6u7kZvVGFqkjp9RKIRQqBeiJzDLglAYusMXiodrcPFwEBw+nwinbfmzH3oLQeHk0PjuITAzB8F3OLEy7yjvmJY4RiNkpDKrm7WFQuXZBcP4kCqFgIMWEoGN/zle0IjE/PlR8ZzwDePLmXMatPR3AzUc3dEsROZhC8KPX8IYtGKJzoJpqUdxsmuLMDfCxTVBo2iFoOZxwm6J7z+H3o89rCW/2a6Yixwmr7FNLHXZJ/KJPAzjjpDwCJJDcPJaDKEsvhsIMyilZDAcKXqkYc38qekRAS9N50VPl3kua4e46CFNd9nfhVxA0c7vUsOuBG7vRVvFfe1LfWdZ3bkZmbNvJ3I7ilih5oChRs6XpBQz1M87QeASgSZ19/bkmFJRiEWJflFJ2KapzZkr96PEsog7Hk2E7qC1aZTqljduVr7J5a91JFM486Oo0M3gIs3TVrQ5CP6ww0xhK7hk19wYA1F0pCFl0fXtp7T1SqFndzeJwtKWwf5+VdC51+QY1pl+/aWeO1hyUnhWpxSnWpIx1H7VLEirIUw2/sQou2UIjW8G8pRiAC
    username: AgBGz0pvBdj50di0IlZU7pRnNnsyAJcV1xY+1naTODsP2KHc4n+FOFcOiu5cmQKDQmm1o8zZdfbN4248u0huUFd2QWeidkE88uMUTBTQPEKAE3RiLmZMm1Pnpll4wSS5WIBski5Ccwwe/KUOWiT2S0rwf6FtEflFpTbTsYaLhWwVINoSJO2zR8sKoIwILToU5mirT+vZ2Y1ej+n0caUcAtpKe3MOWOVUD58Uv9v/MCDm4kQcDzB168q3WwtDG6qoDGoiDtMsWS8TqClHKXDzzUPyHD/fEumbC25/ERRheXiSxA4t3rJKlW5L1XkuZvJv3ChGtSH56L1pvPMG31Vc8JYUylJufBKRmMirjBskKjh6bGs+t631Kl3uaIfwC2Yltb/kcPAPbatOQ+nys7/4l+hFXQAeZIf69udzzMSTwcpBX3aOIGogMqlywbciQ+qHD8ZosmENxh6ZSxsh09703ZUkMJ5epi9N+WXGOyCXAJ+CoLCn6eefXVNcTzcknzzjFedjfw5mAoJ9ZSrufP02UmZIKH5IalR0k3kiZyL8hM21d/U6PV+NuvZwwK7A73ww79BaxYspJmlmWF/G6xWPIOuhNfGDOBnbvjJwSl00FxvzC6zapsWG/xOpdbwbXvlaoFOHPsPjP7BcP0m+GkNHgGw0kWpNspZtkP14feP2izJEbpBNUpN+xr9Lmz0t9Ei3UpZw5bKDrw==
  template:
    metadata:
      name: planka-admin
      namespace: planka
