---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: alertmanager-incident-webhook
  namespace: hermes2
spec:
  encryptedData:
    ALERTMANAGER_BEARER_TOKEN: AgCFIqxUuUmnErnyiBydOlFXaCcRhQdO4+zugAkBsgxvRFeRNhCNMORcykhLGSsu+TDZJb7Syx/ftT4Uk75tYmonAwcpYFnXmRO9HN3O352VUyjkKh7gMXVkmufYmDHB3fUOebZGjPTdyiBNo7+akhH4uTTxrqplVzBtDDdKm1eZouYsQdvNqkIqDpuJN5zlpNxFhWA8FpNcuoTgcD/LnQneTskMzieZ+SmABZTrLBeswdjlkB6hasD2k+0WOry5wHnFLv/YwFTpVsExhHFlnMvYb7HhEJiJz24CrJLkCJS7AUE3XwRmtQTgkKMmsk8Qt6yNTddJXOQ7SXDF2BEE2hcXzhHqkVGc4yJlJNC6m0nPCo8d3K7JkW22+OAHJHoQqdJ3yW1k8bJqHk2En/DOK9p2dVWWo7iRjRzUkCCZwiEvNXz3I/w0O9M0bCB4xcbSORp3joIIdHe9P2fYvyvaZKK/EY6xSctvcmM9gSsRDg6oXn25SR4L66jx0f0r4jmsQ8Z0hGh17L7M79cHjqm4rMGptCBpcyRPdW1fzUxsNJRmAoJXVzH2hXGMo+7jjNjHAwke427m4EHzy29jKRnvZ6AAAH6BBRZae6cum571bbIfx4P7yz5hmqxaOhjdsKKXFKyrylqKI7zsGiKlGOQ1Ha/KPtHq94GRHRFCGzJCMsP6Jd2AVJsSZS4V7wYVKciN4FhrV6/Ke9Qet8HRDcbdLhuTHO13NBMehx6EwSgLhZSeYZxpHkDbjMdSRuK9
    WEBHOOK_SECRET: AgCXbJZ05Guqm6rRVZw34/WtiRF15L4PlW7TH80MZ4FYeasT5a1W8s6HR+WpgDoWGanzUySIX1/8dAqh7fgLoyyfLiBZL92ublPHu4GQqpC84jhQqUmoW8uacD7/qkD8HX7NaX0R3Sjah4Lhf+wvmhpRlcSfU4FCmr324MfeeGGA2c0r56gVRULUI4ML3C2NoLo1eLT33BQi/AsfMKZ8pAMmHVblaJlDVQKhBUtwWUElnab3+YpGf66abDxQSPiOgMW5rBd/9gwtQEmk6bH9zlBzXgY429tK/8i5tmh+s7EInS2lED68oInu9Qfi8pHb1dDHVzCCSmS6kbM9jQu7RubmeddkRCbFpXxb7gyzgx9MDj1DtV69+DAnSR85rw+lpWL9AQ5Ul2uonDT1uXUiPJTKIi71WkpyL4yRTIzlLJuZWYQYzjqsI/HkC0OBVvOBZdp7LKIMrbZnAKUMV1nnoi+9pYWjNAehBa1XOl6KsgwcBZohhRRAjqtCe7ceHwTa2t/JXF2tUPjUGXrOvBDHe3iPJFK9m9r49NuZvfbRIOD3/rX0LCx8r3fQHyxT8myy7JgzqJ01P7Qta9PNnvAZPN7oHhP+DHS697KE/Ei6DvpSL3IP6mpCpSWwJ1UBcNlUQQuZ406hCRcAikmEXclX11b53zKljbN/46zOY0NJKk09/j9yaUkNPxhD5+KlXH3BN9pVEm9N1sGz2Ai0kEBghgJe6aVaF32sLtSzKeSJ8EfW1XOiocvK01ki3AnD
  template:
    metadata:
      name: alertmanager-incident-webhook
      namespace: hermes2
    type: Opaque
