apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cognee-postgres
  namespace: hermes2
spec:
  encryptedData:
    POSTGRES_PASSWORD: AgA3is+dBoGhhElAfWYZ1AsTqbrV0KgrruyLWsF+rNcKG6CEuEPwl8DEJR/UCJQofo1fMhNUJ/Tuq3B0gmrrBP35XjvrsmdnkoantRR7uenNYHn/9aci8JemgVgX8p8hThAHHLYC1+ibcGfoLz92bpkPaJ7kF27fTka3XKg4187aI0vKmuvxaPaxcv4Psm2EDAwz+RycR13ocWJgNa2lW7Ugpum1/uHxOH2ilvHXUJLCy2kCT6WUWfmZB/PIDMKHLxfhi4KkrbxCtqzFlfJ+IT3oa9x1RPzZrhL3oztYrSDuVr1PG6z8OfkwH1V3fMmUF+D+pBA+rMSJoXjbshKsaftPcPqAB2diwnjQ4GlolhuYymxD8ssDMM89oWKP6GkvS1oQEU4XRKRVd33xC/RPdvkBadZRMVH0qhVPbKt+WHUVO/EogO1s01nVXRuDs9e0w+hps4JIoGxNS8Jiu2Yjmkm+EienWdTuYOugio4zwd6UsXtIpj6u8nUeGN2Z1Bl20N8wtBUMy0oW8gpMRUeVKTGsiijQwB8qLcjxSSAqfzSCc2/2FU21BvJmQAE4SxlVRmI8Viz3DaXcscedkh4qL89frQlxb7TPjkt2deDlYoXObQyB2GAG14H4JxLqSH4ajXz6jwH0PBN17kf/bkMF7U1nqQ9TgZReTgdXV1TV2TyqvSymVyKq/iE7K6GeMAnVXmd5IPLJPWPeki5pn/H2LByyO1hTlHSLf/ategeD9hyvp7uf2tJR37I7qGTD0w==
  template:
    metadata:
      name: cognee-postgres
      namespace: hermes2
