---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: hermes2-cognee-openai
  namespace: hermes2
spec:
  encryptedData:
    LLM_API_KEY: AgCsWjri3drBvYzyw+IJHEwmmMFgEa9eHonDJMUMPx9x7mh2ys5luF+Z1sBC56DJ8/s5Zoax2WwUFJjrWw+pen+X0+hBOZarWCXPFtw9dTyXZRd0kMGuJiCQ3L5k8oTEfAjrIhYJGKtXokjnS0O/pivJV5YJz+e6qqYnyrJP056YlJbJ6LpPFQJO9BlaWPBBx2x1znAsAXTgXP8NYRimL5MELABnnWs81vBmzohABG5EQXyTxkanZVqfI83aKn+XvRT+dUzW0RRILyWMlRev2dm9h7kPImucGnwHuRciZhb//MNIfnBn6YnYsCrKxtJj1t1gb4T30OCACwoADMU+3iilIH1+fGoEMmUOdv8eeQefl5Jb6gZkVuQwGir1DqFNSy+KL8/ZoLDIof4byKeqNW8h2V8kxXRJL5UB21wPWIVuC7nE30R9Ogq423W0K12t48CX/w1uspPRqbz5uHTAQ+gXq2TIUNfcMr5HjzaN5LRZGXz+JVyGZcJWnDZBOHk8/ukYPVmosZ1Cx+ejobEL3KInhNuZqpjkpxIlA+Zgy1brn4kfEQ1/eeNEm6ku+bl9fMwDLK9xfHwCkOYkGCmqGBLJKO8cSN9pqzdKcVR9RRnvoxUu3FVJEvKy92VA9lZeCa2MLSfzK4epaEgnsWPc7YxWEQjsx670/bGb+m/zcGjnCfAE5McdU2xWHdksLRpca3Oyqr2cTHXL+cZORcMlOaQFB9y/cl5Xh1RaQ4tnBAfHUt/rL0o95AvpVagj0182lcHHOigRhMMNqYvfhoTMqR50p8RUtFSJddkiO00c1Lan6rUDBcCnvHTz2nKY9GYrsyfuQivQ+aRNwi14kypHtoh42/X8FksAPoKq0MOaqfqWKd/5KP4ZNk7mbshQGIYvCwKYSMKKnBxRVZz58EtGIgGqI6jzgg==
  template:
    metadata:
      name: hermes2-cognee-openai
      namespace: hermes2
    type: Opaque
