---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: hhccia-machine-creds
  namespace: hermes2
spec:
  encryptedData:
    app-password: AgBiKiQOQL2t9czh4mtesHVFQGfwax1CFi7uQpk/TGRg+pSMJ5EortDLkd86aFJZwnvEOQAFqRbIT2MQRcET9GMtP+xImdAQCwJt2pkvpNYnrljQwzV8h75w2z1tO1fMGeg0SL6BmQ2OZ/aDEcznWYoqQHVAYUW+BWo3Q8alxXC+VQ++y7PJybC/dUJBC0dSO5+4EUnoCNl9D2o6FUPh217XlJbv1jN5OIOGTLyY5kLNLM94Cocf8Zyi8eIA0rGJUqJDeHTtZx6+gFyrz3cADj1CIX9KQFRwSzhEUITQyE9Ik1Z5wY45F/wDWTpVnUbIkbwvdT/hF2Rvepyti1glt4BSt5z8jfWUn1rOBZ/2wgVZmHmgNEKQeaEwWGraQPMOZmFMWDE8FjkRyeV82XSqjInrij3WvEQCchMB0DltwKWlQpxXIwivama03eIa5I9M333z8/C9H0fzTT9ezLTrs537TibO4aJQdKTH/BJxRkEI9XRN5CYb0rt/S0H7NZnmE17iq8eTg33VlFPCxZLvmPEEvJ8/sWHdDcBi49vOaTgOg9oYLZpF3+PpsomVEPGeUX19YlM1T+gHFRTA4XwQC6z1Fc6hWVrcl0ZTB+PsnpO6SA1RL65CR0wwjuXiUWX5cp2a9Bl5WQeO4xd8UXGpHivz7AmmJnO1ujKI6+33ip1BTJLzTmW4CDhl9JHwSN3DReDdc8l1EnMfkXLZKvBf4OgsHg743Yi3pXePFc/h0ZfugqxfaYDavFoP/qN4WScDTrstCBRrixYCaIp5L42mkbCiNc4qbiJTKBgrhiI1ZJW0RFwqfpbBgw==
  template:
    metadata:
      name: hhccia-machine-creds
      namespace: hermes2
