apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: irupe-cluster
  namespace: irupe  # The namespace where you want your database
spec:
  instances: 1
  primaryUpdateStrategy: unsupervised
  storage:
    size: 10Gi
