{
 "title": "kube-state-metrics-v2",
 "description": "Summary metrics about kube-state-metrics v2 version(https://github.com/kubernetes/kube-state-metrics); Referenced 6417",
 "tags": [
  "kubernetes",
  "kubernetes-app"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "cluster", "query": ".+" },
   {
    "name": "node",
    "query": "label_values(kube_node_info, node)"
   },
   {
    "name": "namespace",
    "query": "label_values(kube_namespace_created, namespace)"
   },
   { "name": "datasource", "query": "${VAR_DATASOURCE}" }
  ]
 },
 "panels": [
  { "title": "Cluster", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Cluster Pod Requested",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 1 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_pod_info{node=~\"$node\"}) / sum(kube_node_status_allocatable{resource=\"pods\",node=~\"$node\"})"
    }
   ]
  },
  {
   "title": "Cluster CPU Requested",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 1 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests{resource=\"cpu\",node=~\"$node\"})/ sum(kube_node_status_allocatable{node=~\"$node\",resource=\"cpu\"})"
    }
   ]
  },
  {
   "title": "Cluster Memory  Requested",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 1 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests{resource=\"memory\",node=~\"$node\"}) / sum(kube_node_status_allocatable{node=~\"$node\",resource=\"memory\"})"
    }
   ]
  },
  {
   "title": "Cluster Pod Capacity",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "short", "label": "pods" }
   ],
   "targets": [
    {
     "expr": "sum(kube_node_status_allocatable{resource=\"pods\",node=~\"$node\"})",
     "legendFormat": "allocatable"
    },
    {
     "expr": "sum(kube_pod_info{node=~\"$node\"})",
     "legendFormat": "requested"
    }
   ]
  },
  {
   "title": "Cluster CPU Capacity",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 5 },
   "yaxes": [
    { "format": "short", "label": "cores" }
   ],
   "targets": [
    {
     "expr": "sum(kube_node_status_capacity{node=~\"$node\",resource=\"cpu\"})",
     "legendFormat": "allocatable"
    },
    {
     "expr": "sum(kube_node_status_allocatable{node=~\"$node\",resource=\"cpu\"})",
     "legendFormat": "capacity"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{resource=\"cpu\",node=~\"$node\"})",
     "legendFormat": "requested"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{resource=\"cpu\",node=~\"$node\"})",
     "legendFormat": "limited"
    }
   ]
  },
  {
   "title": "Cluster Mem Capacity",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 5 },
   "yaxes": [
    { "format": "bits" }
   ],
   "targets": [
    {
     "expr": "sum(kube_node_status_allocatable{node=~\"$node\",resource=\"memory\"})",
     "legendFormat": "allocatable"
    },
    {
     "expr": "sum(kube_node_status_capacity{node=~\"$node\",resource=\"memory\"})",
     "legendFormat": "capacity"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{resource=\"memory\",node=~\"$node\"})",
     "legendFormat": "requested"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{resource=\"memory\",node=~\"$node\"})",
     "legendFormat": "limited"
    }
   ]
  },
  {
   "title": "Node",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "collapsed": true,
   "panels": [
    {
     "title": "Number Of Nodes",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 4, "x": 0, "y": 11 },
     "format": "none",
     "valueName": "avg",
     "targets": [
      { "expr": "sum(kube_node_info)" }
     ]
    },
    {
     "title": "Nodes Unavailable",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 4, "x": 4, "y": 11 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(kube_node_spec_unschedulable)"
      }
     ]
    },
    {
     "title": "Node NotReady",
     "type": "graph",
     "gridPos": { "h": 3, "w": 8, "x": 8, "y": 11 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "kube_node_status_condition{condition=\"Ready\",status=\"false\"}==1",
       "legendFormat": "{{node}}"
      }
     ]
    },
    {
     "title": "Node Pressure",
     "type": "graph",
     "gridPos": { "h": 3, "w": 8, "x": 16, "y": 11 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "kube_node_status_condition{condition=\"DiskPressure\",status=\"true\"}==1",
       "legendFormat": "{{node}} {{condition}}"
      },
      {
       "expr": "kube_node_status_condition{condition=\"MemoryPressure\",node=~\"$node\",status=\"true\"}==1",
       "legendFormat": "{{node}} {{condition}}"
      },
      {
       "expr": "kube_node_status_condition{condition=~\"PIDPressure\",node=~\"$node\",status=\"true\"}==1",
       "legendFormat": "{{node}} {{condition}}"
      }
     ]
    },
    {
     "title": "node number",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 14 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      { "expr": "sum(kube_node_info)" }
     ]
    }
   ]
  },
  {
   "title": "Deployments",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "collapsed": true,
   "panels": [
    {
     "title": "Deployment Replicas - Up To Date",
     "type": "table-old",
     "gridPos": { "h": 5, "w": 6, "x": 0, "y": 17 },
     "targets": [
      {
       "expr": "kube_deployment_status_replicas{namespace=~\"$namespace\"}",
       "legendFormat": "{{ deployment }}"
      }
     ]
    },
    {
     "title": "Deployment Replicas",
     "type": "singlestat",
     "gridPos": { "h": 5, "w": 6, "x": 6, "y": 17 },
     "format": "none",
     "valueName": "avg",
     "targets": [
      {
       "expr": "sum(kube_deployment_status_replicas{namespace=~\"$namespace\"})"
      }
     ]
    },
    {
     "title": "Deployment Replicas - Updated",
     "type": "singlestat",
     "gridPos": { "h": 5, "w": 6, "x": 12, "y": 17 },
     "format": "none",
     "valueName": "avg",
     "targets": [
      {
       "expr": "sum(kube_deployment_status_replicas_updated{namespace=~\"$namespace\"})"
      }
     ]
    },
    {
     "title": "Deployment Replicas - Unavailable",
     "type": "singlestat",
     "gridPos": { "h": 5, "w": 6, "x": 18, "y": 17 },
     "format": "none",
     "valueName": "avg",
     "targets": [
      {
       "expr": "sum(kube_deployment_status_replicas_unavailable{namespace=~\"$namespace\"})"
      }
     ]
    }
   ]
  },
  {
   "title": "Statefuleset",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "collapsed": true,
   "panels": [
    {
     "title": "Statefulset Replicas - Up To Date",
     "type": "table-old",
     "gridPos": { "h": 5, "w": 6, "x": 0, "y": 7 },
     "targets": [
      {
       "expr": "kube_statefulset_status_replicas_ready{namespace=~\"$namespace\"}",
       "legendFormat": "{{ statefulset}}"
      }
     ]
    },
    {
     "title": "Statefulset replicas",
     "type": "graph",
     "gridPos": { "h": 5, "w": 12, "x": 6, "y": 7 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "kube_statefulset_status_replicas_ready{namespace=~\"$namespace\"}/kube_statefulset_status_replicas{namespace=~\"$namespace\"}*100",
       "legendFormat": "{{statefulset}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Pods",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 },
   "collapsed": true,
   "panels": [
    {
     "title": "Pods restart in 30m",
     "type": "table-old",
     "gridPos": { "h": 9, "w": 6, "x": 0, "y": 26 },
     "targets": [
      {
       "expr": "changes(kube_pod_container_status_restarts_total{namespace=~\"$namespace\"}[30m])>1",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Evicted",
     "type": "graph",
     "gridPos": { "h": 9, "w": 6, "x": 6, "y": 26 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "kube_pod_status_reason{namespace=~\"$namespace\", reason=\"Evicted\"}==1",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Pods Running",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 12, "x": 12, "y": 26 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(kube_pod_status_phase{namespace=~\"$namespace\", phase=\"Running\"})"
      }
     ]
    },
    {
     "title": "Pods Succeeded",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 6, "x": 12, "y": 29 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(kube_pod_status_phase{namespace=~\"$namespace\", phase=\"Succeeded\"})"
      }
     ]
    },
    {
     "title": "Pods Failed",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 6, "x": 18, "y": 29 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(kube_pod_status_phase{namespace=~\"$namespace\", phase=\"Failed\"})"
      }
     ]
    },
    {
     "title": "Pods Pending",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 6, "x": 12, "y": 32 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(kube_pod_status_phase{namespace=~\"$namespace\", phase=\"Pending\"})"
      }
     ]
    },
    {
     "title": "Pods Unknown",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 6, "x": 18, "y": 32 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(kube_pod_status_phase{namespace=~\"$namespace\", phase=\"Unknown\"})"
      }
     ]
    }
   ]
  },
  {
   "title": "Containers",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 },
   "collapsed": true,
   "panels": [
    {
     "title": "Containers Running",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 6, "x": 0, "y": 15 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(kube_pod_container_status_running{namespace=~\"$namespace\"})"
      }
     ]
    },
    {
     "title": "Containers Waiting",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 6, "x": 6, "y": 15 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(kube_pod_container_status_waiting{namespace=~\"$namespace\"})"
      }
     ]
    },
    {
     "title": "Containers Terminated",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 6, "x": 12, "y": 15 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(kube_pod_container_status_terminated{namespace=~\"$namespace\"})"
      }
     ]
    },
    {
     "title": "Containers Restarts (Last 30 Minutes)",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 6, "x": 18, "y": 15 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(changes(kube_pod_container_status_restarts_total{namespace=~\"$namespace\"}[30m]))"
      }
     ]
    },
    {
     "title": "CPU Cores Requested by Containers",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 12, "x": 0, "y": 18 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(kube_pod_container_resource_requests_cpu_cores{namespace=~\"$namespace\"})"
      }
     ]
    },
    {
     "title": "Memory Requested By Containers",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 12, "x": 12, "y": 18 },
     "format": "decbytes",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(kube_pod_container_resource_requests_memory_bytes{namespace=~\"$namespace\" })"
      }
     ]
    }
   ]
  },
  {
   "title": "HPA",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "collapsed": true,
   "panels": [
    {
     "title": "hpa",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 7 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "kube_hpa_status_current_replicas{namespace=~\"$namespace\"}",
       "legendFormat": "current_{{hpa}}"
      },
      {
       "expr": "kube_hpa_spec_max_replicas{namespace=~\"$namespace\"}",
       "legendFormat": "max_{{hpa}}"
      },
      {
       "expr": "kube_hpa_spec_min_replicas{namespace=~\"$namespace\"}",
       "legendFormat": "min_{{hpa}}"
      }
     ]
    },
    {
     "title": "total-hpa-current",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 15 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(kube_hpa_status_current_replicas{hpa=~\".*\"})",
       "legendFormat": "kube_hpa_status_current_replicas"
      }
     ]
    },
    {
     "title": "current==max",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 23 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "kube_hpa_status_current_replicas{hpa=~\".*\"} == kube_hpa_spec_max_replicas{hpa=~\".*\"}",
       "legendFormat": "{{hpa}}"
      }
     ]
    },
    {
     "title": "current==min",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 23 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "kube_hpa_status_current_replicas{hpa=~\".*\"} == kube_hpa_spec_min_replicas{hpa=~\".*\"}",
       "legendFormat": "{{hpa}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Jobs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "collapsed": true,
   "panels": [
    {
     "title": "Jobs Succeeded",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 8, "x": 0, "y": 8 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(kube_job_status_succeeded{namespace=~\"$namespace\"})"
      }
     ]
    },
    {
     "title": "Job last success time from now",
     "type": "table-old",
     "gridPos": { "h": 9, "w": 8, "x": 8, "y": 8 },
     "targets": [
      {
       "expr": "(time()-kube_job_status_completion_time{namespace=~\"$namespace\"})/60/60/24>1",
       "legendFormat": "{{job_name}}"
      }
     ]
    },
    {
     "title": "Job failed",
     "type": "table-old",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 8 },
     "targets": [
      {
       "expr": "kube_job_status_failed{namespace=~\"$namespace\"}>1",
       "legendFormat": "{{job_name}}"
      }
     ]
    },
    {
     "title": "Jobs Active",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 8, "x": 0, "y": 11 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(kube_job_status_active{namespace=~\"$namespace\"})"
      }
     ]
    },
    {
     "title": "Jobs Failed",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 8, "x": 0, "y": 14 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(kube_job_status_failed{namespace=~\"$namespace\"})"
      }
     ]
    }
   ]
  },
  {
   "title": "PVC",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "collapsed": true,
   "panels": [
    {
     "title": "pvc is bound",
     "type": "singlestat",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 17 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(kube_persistentvolumeclaim_status_phase{phase=\"Bound\"}==1)",
       "legendFormat": "{{persistentvolumeclaim=}}"
      }
     ]
    },
    {
     "title": "pvc is not bound",
     "type": "singlestat",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 17 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(kube_persistentvolumeclaim_status_phase{phase!=\"Bound\"}==1)",
       "legendFormat": "{{persistentvolumeclaim=}}"
      }
     ]
    },
    {
     "title": "pvc",
     "type": "table-old",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
     "targets": [
      {
       "expr": "kube_persistentvolumeclaim_resource_requests_storage_bytes/1024/1024/1024",
       "legendFormat": "{{persistentvolumeclaim}}"
      }
     ]
    }
   ]
  }
 ]
}
{
 "title": "Cluster — Nodos (comparativa)",
 "tags": [
  "cluster",
  "nodes",
  "health"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "panels": [
  { "title": "Resumen del cluster", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Nodos Ready (esperado 3)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_node_status_condition{condition=\"Ready\",status=\"true\"})"
    }
   ]
  },
  {
   "title": "Pods (cluster)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 5, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "count(kube_pod_info)" }
   ]
  },
  {
   "title": "CPU cluster %",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 10, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 * (1 - avg(rate(node_cpu_seconds_total{mode=\"idle\"}[5m])))"
    }
   ]
  },
  {
   "title": "Memoria cluster %",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 * (1 - sum(node_memory_MemAvailable_bytes) / sum(node_memory_MemTotal_bytes))"
    }
   ]
  },
  {
   "title": "etcd con líder (esperado 3)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(etcd_server_has_leader)" }
   ]
  },
  { "title": "Comparativa por nodo (ahora)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "CPU % por nodo",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "legendFormat": "{{node}}",
     "expr": "100 - (avg by (node) (rate(node_cpu_seconds_total{mode=\"idle\"}[5m])) * 100)"
    }
   ]
  },
  {
   "title": "Memoria % por nodo",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "legendFormat": "{{node}}",
     "expr": "100 * (1 - node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes)"
    }
   ]
  },
  {
   "title": "Disco raíz (/) % por nodo",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "legendFormat": "{{node}}",
     "expr": "100 - (node_filesystem_avail_bytes{mountpoint=\"/\",fstype!~\"tmpfs|overlay|squashfs|ramfs\"} / node_filesystem_size_bytes{mountpoint=\"/\"} * 100)"
    }
   ]
  },
  { "title": "Series temporales por nodo", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "CPU % por nodo",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "legendFormat": "{{node}}",
     "expr": "100 - (avg by (node) (rate(node_cpu_seconds_total{mode=\"idle\"}[5m])) * 100)"
    }
   ]
  },
  {
   "title": "Memoria % por nodo",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "legendFormat": "{{node}}",
     "expr": "100 * (1 - node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes)"
    }
   ]
  },
  {
   "title": "Disco raíz (/) % por nodo",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "legendFormat": "{{node}}",
     "expr": "100 - (node_filesystem_avail_bytes{mountpoint=\"/\",fstype!~\"tmpfs|overlay|squashfs|ramfs\"} / node_filesystem_size_bytes{mountpoint=\"/\"} * 100)"
    }
   ]
  },
  {
   "title": "Load average por nodo (nodos de 4 cores)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "legendFormat": "1m · {{node}}", "expr": "node_load1" },
    { "legendFormat": "15m · {{node}}", "expr": "node_load15" }
   ]
  },
  { "title": "Red y estado", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 } },
  {
   "title": "Red recibida (RX) por nodo",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "legendFormat": "{{node}}",
     "expr": "sum by (node) (rate(node_network_receive_bytes_total{device=~\"en.*|eth.*\"}[5m]))"
    }
   ]
  },
  {
   "title": "Red transmitida (TX) por nodo",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "legendFormat": "{{node}}",
     "expr": "sum by (node) (rate(node_network_transmit_bytes_total{device=~\"en.*|eth.*\"}[5m]))"
    }
   ]
  },
  {
   "title": "Pods por nodo",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "legendFormat": "{{node}}",
     "expr": "count by (node) (kube_pod_info)"
    }
   ]
  },
  {
   "title": "etcd: líder por nodo (1 = ok)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "legendFormat": "{{instance}}", "expr": "etcd_server_has_leader" }
   ]
  }
 ]
}
{
 "title": "Node Alerts — CPU / Memory / Disk",
 "tags": [
  "nodes",
  "alerts"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "CPU usage % — alert: NodeHighCpu (> 80% for 5m)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - (avg by (instance) (rate(node_cpu_seconds_total{mode=\"idle\"}[5m])) * 100)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Memory usage % — alert: NodeHighMemory (> 85% for 5m)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 * (1 - (node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Disk free % — alert: NodeDiskSpaceLow (< 15% for 10m)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "node_filesystem_avail_bytes{fstype!~\"tmpfs|overlay|squashfs|ramfs\"} / node_filesystem_size_bytes{fstype!~\"tmpfs|overlay|squashfs|ramfs\"} * 100 and node_filesystem_readonly == 0",
     "legendFormat": "{{instance}} {{mountpoint}}"
    }
   ]
  }
 ]
}
{
 "title": "Alertas — Estado de infraestructura",
 "description": "Estado de todas las alertas de infraestructura en un solo lugar. Tabla de alertas activas + contadores + historial vía métrica ALERTS (reglas Prometheus); sección de alertas de logs vía Loki (las 4 alertas del ruler). Lo que no aparece está OK.",
 "tags": [
  "alerts",
  "infraestructura",
  "prometheus",
  "loki"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "**Cómo leer este tablero** — **Watchdog** debe estar siempre *activo* (es el dead-man's switch; si se apaga, Prometheus/Alertmanager están caídos). La tabla **Alertas activas** lista toda alerta de Prometheus firing/pending (sin el Watchdog): **vacía = infraestructura sana**. La sección **Alertas de logs** muestra la señal en vivo de las 4 alertas del ruler de Loki (cada panel se pone rojo cuando alcanzaría su umbral). Una alerta en estado **OK** no aparece: su ausencia significa que está sana. Las alertas gestionadas por Grafana (costo Gemini, backlog del pipeline) viven en *Alerting* de Grafana, no aquí."
   }
  },
  { "title": "Resumen (reglas Prometheus)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 } },
  {
   "title": "Watchdog (heartbeat)",
   "type": "stat",
   "description": "Dead-man's switch (vector(1)): DEBE estar siempre activo. Si marca AUSENTE, Prometheus o Alertmanager están caídos (healthchecks.io te avisa).",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(ALERTS{alertname=\"Watchdog\",alertstate=\"firing\"}) or vector(0)"
    }
   ]
  },
  {
   "title": "Críticas firing",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(ALERTS{alertstate=\"firing\",severity=\"critical\"}) or vector(0)"
    }
   ]
  },
  {
   "title": "Warnings firing",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(ALERTS{alertstate=\"firing\",severity=\"warning\"}) or vector(0)"
    }
   ]
  },
  {
   "title": "Alertas pending",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(ALERTS{alertstate=\"pending\"}) or vector(0)"
    }
   ]
  },
  {
   "title": "Alertas activas — reglas Prometheus (métrica ALERTS, sin Watchdog)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 }
  },
  {
   "title": "Alertas activas ahora (firing / pending)",
   "type": "table",
   "description": "Toda alerta de Prometheus actualmente firing o pending, con sus etiquetas (alertname, severity, alertstate, instance, …). Excluye el Watchdog. Vacía = ninguna alerta real activa = infraestructura sana.",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "ALERTS{alertstate=~\"firing|pending\", alertname!=\"Watchdog\"}"
    }
   ]
  },
  {
   "title": "Alertas de logs (ruler de Loki) — señal en vivo",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 }
  },
  {
   "title": "CNPGBackupFailed (10m) — alerta > 0",
   "type": "stat",
   "description": "Errores del plugin barman-cloud (critical). Mismo LogQL que la alerta CNPGBackupFailed del ruler de Loki. Rojo = alcanzaría el umbral.",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time({namespace=\"hhccia-v2\", container=\"plugin-barman-cloud\"} | json | level=\"error\" [10m]))"
    }
   ]
  },
  {
   "title": "CNPGWalArchiveErrorsLog (10m) — alerta > 0",
   "type": "stat",
   "description": "'archive command failed' en postgres (warning). Mismo LogQL que la alerta CNPGWalArchiveErrorsLog.",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time({namespace=\"hhccia-v2\", container=\"postgres\"} |= \"archive command failed\" [10m]))"
    }
   ]
  },
  {
   "title": "GeminiAccessErrors (5m) — alerta > 3",
   "type": "stat",
   "description": "Respuestas HTTP 4xx/5xx de Gemini (warning). Mismo LogQL que la alerta GeminiAccessErrors (>3 en 5m).",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time({namespace=\"hhccia-v2\", container=\"hhccia-core\"} |= \"generativelanguage.googleapis.com\" |~ \"HTTP/1.1 [45]\" [5m]))"
    }
   ]
  },
  {
   "title": "GeminiRecordsDeadLettered (10m) — alerta > 0",
   "type": "stat",
   "description": "Registros enviados a dead-letter (critical). Mismo LogQL que la alerta GeminiRecordsDeadLettered.",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time({namespace=\"hhccia-v2\", container=\"hhccia-core\"} |= \"dead-lettering\" [10m]))"
    }
   ]
  },
  {
   "title": "Señal de las alertas de logs en el tiempo",
   "type": "timeseries",
   "description": "Evolución de las 4 señales de las alertas del ruler de Loki (cuenta por ventana). Deben vivir en 0; un pico es lo que dispara la alerta correspondiente.",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "legendFormat": "CNPG backup errors",
     "expr": "sum(count_over_time({namespace=\"hhccia-v2\", container=\"plugin-barman-cloud\"} | json | level=\"error\" [$__auto]))"
    },
    {
     "legendFormat": "WAL archive failed",
     "expr": "sum(count_over_time({namespace=\"hhccia-v2\", container=\"postgres\"} |= \"archive command failed\" [$__auto]))"
    },
    {
     "legendFormat": "Gemini 4xx/5xx",
     "expr": "sum(count_over_time({namespace=\"hhccia-v2\", container=\"hhccia-core\"} |= \"generativelanguage.googleapis.com\" |~ \"HTTP/1.1 [45]\" [$__auto]))"
    },
    {
     "legendFormat": "dead-letters",
     "expr": "sum(count_over_time({namespace=\"hhccia-v2\", container=\"hhccia-core\"} |= \"dead-lettering\" [$__auto]))"
    }
   ]
  },
  { "title": "Historial (reglas Prometheus)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 } },
  {
   "title": "Alertas firing en el tiempo (por alerta)",
   "type": "timeseries",
   "description": "Cuántas instancias de cada alerta de Prometheus estuvieron firing a lo largo del rango. Un escalón arriba = la alerta se disparó; vuelve a 0 al resolverse.",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "legendFormat": "{{alertname}}",
     "expr": "count by (alertname) (ALERTS{alertstate=\"firing\"})"
    }
   ]
  },
  {
   "title": "Firing por severidad (críticas vs warnings)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "count(ALERTS{alertstate=\"firing\",severity=\"critical\"}) or vector(0)"
    },
    {
     "expr": "count(ALERTS{alertstate=\"firing\",severity=\"warning\"}) or vector(0)"
    }
   ]
  }
 ]
}
{
 "title": "HHCCIA — Backlog del ingestor (NATS JetStream)",
 "tags": [
  "hhccia",
  "pipeline",
  "nats"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Backlog ahora (num_pending) — alerta > 10",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(jetstream_consumer_num_pending{stream_name=\"HHCCIA\", consumer_name=\"core-ingestor\"})"
    }
   ]
  },
  {
   "title": "En vuelo (num_ack_pending)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(jetstream_consumer_num_ack_pending{stream_name=\"HHCCIA\", consumer_name=\"core-ingestor\"})"
    }
   ]
  },
  {
   "title": "Reintentos (num_redelivered)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(jetstream_consumer_num_redelivered{stream_name=\"HHCCIA\", consumer_name=\"core-ingestor\"})"
    }
   ]
  },
  {
   "title": "Backlog del ingestor en el tiempo — línea de alerta en 10",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "legendFormat": "num_pending (backlog)",
     "expr": "max(jetstream_consumer_num_pending{stream_name=\"HHCCIA\", consumer_name=\"core-ingestor\"})"
    },
    {
     "legendFormat": "num_ack_pending (en vuelo)",
     "expr": "max(jetstream_consumer_num_ack_pending{stream_name=\"HHCCIA\", consumer_name=\"core-ingestor\"})"
    },
    {
     "legendFormat": "num_redelivered (reintentos)",
     "expr": "max(jetstream_consumer_num_redelivered{stream_name=\"HHCCIA\", consumer_name=\"core-ingestor\"})"
    }
   ]
  }
 ]
}
{
 "title": "MedAudit — Salud de consumers (NATS JetStream)",
 "tags": [
  "hhccia",
  "pipeline",
  "nats",
  "consumers"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Consumers del core presentes (esperados: 4) — alerta: < 4 por 10m",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(jetstream_consumer_num_pending{stream_name=\"HHCCIA\", consumer_name=~\"core-.*\"}) or vector(0)"
    }
   ]
  },
  {
   "title": "Consumers totales en el stream (core 4 + adapter 2 = 6)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(jetstream_stream_consumer_count{stream_name=\"HHCCIA\"})"
    }
   ]
  },
  {
   "title": "Mensajes retenidos en el stream",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(jetstream_stream_total_messages{stream_name=\"HHCCIA\"})"
    }
   ]
  },
  {
   "title": "Consumers del core presentes en el tiempo — línea de alerta en 4",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "legendFormat": "core-* presentes",
     "expr": "count(jetstream_consumer_num_pending{stream_name=\"HHCCIA\", consumer_name=~\"core-.*\"}) or vector(0)"
    }
   ]
  },
  {
   "title": "Presencia por consumer (1 = vivo · hueco = ausente)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "legendFormat": "{{consumer_name}}",
     "expr": "count by (consumer_name) (jetstream_consumer_num_pending{stream_name=\"HHCCIA\", consumer_name=~\"core-.*\"})"
    }
   ]
  },
  {
   "title": "Backlog (num_pending) + reintentos (num_redelivered) por consumer",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "legendFormat": "pending · {{consumer_name}}",
     "expr": "max by (consumer_name) (jetstream_consumer_num_pending{stream_name=\"HHCCIA\", consumer_name=~\"core-.*\"})"
    },
    {
     "legendFormat": "redelivered · {{consumer_name}}",
     "expr": "max by (consumer_name) (jetstream_consumer_num_redelivered{stream_name=\"HHCCIA\", consumer_name=~\"core-.*\"})"
    }
   ]
  }
 ]
}
{
 "title": "MedAudit — Métricas del core (app)",
 "tags": [
  "hhccia",
  "core",
  "app"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "NATS conectado (publish)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "max(hhccia_bus_connected)" }
   ]
  },
  {
   "title": "Dead-letters 24h — alerta > 0",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(hhccia_bus_messages_total{outcome=~\"dead_letter|permanent|non_json\"}[24h])) or vector(0)"
    }
   ]
  },
  {
   "title": "Costo Gemini 24h (USD derivado)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(hhccia_gemini_cost_usd_total[24h])) or vector(0)"
    }
   ]
  },
  {
   "title": "API p95 (1h)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by (le) (rate(hhccia_http_request_seconds_bucket[1h])))"
    }
   ]
  },
  {
   "title": "Bus: mensajes por subject/outcome (15m) — dead_letter/permanent deben ser 0",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "legendFormat": "{{subject}} · {{outcome}}",
     "expr": "sum by (subject, outcome) (increase(hhccia_bus_messages_total[15m]))"
    }
   ]
  },
  {
   "title": "Gemini: llamadas por outcome (15m) — permanent = billing/quota",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "legendFormat": "{{outcome}}",
     "expr": "sum by (outcome) (increase(hhccia_gemini_calls_total[15m]))"
    }
   ]
  },
  {
   "title": "Gemini: latencia p50 / p95 por kind (30m)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "legendFormat": "p50 · {{kind}}",
     "expr": "histogram_quantile(0.5, sum by (le, kind) (rate(hhccia_gemini_latency_seconds_bucket[30m])))"
    },
    {
     "legendFormat": "p95 · {{kind}}",
     "expr": "histogram_quantile(0.95, sum by (le, kind) (rate(hhccia_gemini_latency_seconds_bucket[30m])))"
    }
   ]
  },
  {
   "title": "Gemini: costo por kind (USD/h, derivado)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "legendFormat": "{{kind}}",
     "expr": "sum by (kind) (increase(hhccia_gemini_cost_usd_total[1h]))"
    }
   ]
  },
  {
   "title": "API: p95 por ruta (15m)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "legendFormat": "{{route}}",
     "expr": "histogram_quantile(0.95, sum by (le, route) (rate(hhccia_http_request_seconds_bucket[15m])))"
    }
   ]
  },
  {
   "title": "DB: pool de conexiones (en uso vs tamaño)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "legendFormat": "en uso", "expr": "max(hhccia_db_pool_in_use)" },
    { "legendFormat": "tamaño del pool", "expr": "max(hhccia_db_pool_size)" },
    {
     "legendFormat": "overflow (>0 = saturado)",
     "expr": "clamp_min(max(hhccia_db_pool_overflow), 0)"
    }
   ]
  }
 ]
}
{
 "title": "CNPG Backups — hhccia-core-db logs",
 "tags": [
  "cnpg",
  "backup",
  "logs"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "Barman plugin errors — backup / WAL / retention (alert: CNPGBackupFailed)",
   "type": "logs",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "{namespace=\"hhccia-v2\", container=\"plugin-barman-cloud\"} | json | level=\"error\""
    }
   ]
  },
  {
   "title": "Postgres WAL archiver failures (alert: CNPGWalArchiveErrorsLog)",
   "type": "logs",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 11 },
   "targets": [
    {
     "expr": "{namespace=\"hhccia-v2\", container=\"postgres\"} |= \"archive command failed\""
    }
   ]
  },
  {
   "title": "All hhccia-core-db logs (context)",
   "type": "logs",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 19 },
   "targets": [
    {
     "expr": "{namespace=\"hhccia-v2\", pod=~\"hhccia-core-db-.*\"}"
    }
   ]
  }
 ]
}
{
 "title": "Gemini — Costo (tokens + USD)",
 "tags": [
  "gemini",
  "cost",
  "hhccia"
 ],
 "time": { "from": "now-30d", "to": "now" },
 "refresh": "30m",
 "panels": [
  {
   "title": "Costo hoy (UTC)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT coalesce(sum(cost_usd),0) AS value FROM gemini_usage_report WHERE created_at >= date_trunc('day', now())"
    }
   ]
  },
  {
   "title": "Costo últimos 7 días",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT coalesce(sum(cost_usd),0) AS value FROM gemini_usage_report WHERE created_at >= now() - interval '7 days'"
    }
   ]
  },
  {
   "title": "Costo últimos 30 días",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT coalesce(sum(cost_usd),0) AS value FROM gemini_usage_report WHERE created_at >= now() - interval '30 days'"
    }
   ]
  },
  {
   "title": "Interacciones (30 días)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT count(*) AS value FROM gemini_usage_report WHERE created_at >= now() - interval '30 days'"
    }
   ]
  },
  {
   "title": "Costo diario por tipo (evaluation vs voice_edit)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "rawSql": "SELECT $__timeGroup(created_at,'1d') AS time, kind AS metric, sum(cost_usd) AS value FROM gemini_usage_report WHERE $__timeFilter(created_at) GROUP BY 1, kind ORDER BY 1"
    }
   ]
  },
  {
   "title": "Costo diario por servicio",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "rawSql": "SELECT $__timeGroup(created_at,'1d') AS time, coalesce(service_code,'sin servicio') AS metric, sum(cost_usd) AS value FROM gemini_usage_report WHERE $__timeFilter(created_at) GROUP BY 1, 2 ORDER BY 1"
    }
   ]
  },
  {
   "title": "Costo por servicio (rango seleccionado)",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 10, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT coalesce(service_code,'sin servicio') AS metric, sum(cost_usd) AS value FROM gemini_usage_report WHERE $__timeFilter(created_at) GROUP BY 1 ORDER BY 2 DESC"
    }
   ]
  },
  {
   "title": "Costo por modelo y tipo (rango seleccionado)",
   "type": "table",
   "gridPos": { "h": 9, "w": 14, "x": 10, "y": 22 },
   "targets": [
    {
     "rawSql": "SELECT model, kind, count(*) AS interacciones, coalesce(sum(total_tokens),0) AS tokens, round(coalesce(sum(cost_usd),0)::numeric,4) AS costo_usd FROM gemini_usage_report WHERE $__timeFilter(created_at) GROUP BY model, kind ORDER BY costo_usd DESC"
    }
   ]
  }
 ]
}
{
 "title": "Gemini — Salud de acceso (errores / éxitos / dead-letter)",
 "tags": [
  "gemini",
  "hhccia",
  "logs",
  "alerts"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "Errores Gemini 4xx/5xx (15m) — alerta: GeminiAccessErrors",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time({namespace=\"hhccia-v2\", container=\"hhccia-core\"} |= \"generativelanguage.googleapis.com\" |~ \"HTTP/1.1 [45]\" [15m]))"
    }
   ]
  },
  {
   "title": "Registros a dead-letter (1h) — alerta: GeminiRecordsDeadLettered",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time({namespace=\"hhccia-v2\", container=\"hhccia-core\"} |= \"dead-lettering\" [1h]))"
    }
   ]
  },
  {
   "title": "Llamadas Gemini OK (15m)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time({namespace=\"hhccia-v2\", container=\"hhccia-core\"} |= \"generativelanguage.googleapis.com\" |= \"200 OK\" [15m]))"
    }
   ]
  },
  {
   "title": "Gemini: errores 4xx/5xx vs éxitos en el tiempo",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(count_over_time({namespace=\"hhccia-v2\", container=\"hhccia-core\"} |= \"generativelanguage.googleapis.com\" |~ \"HTTP/1.1 [45]\" [$__auto]))"
    },
    {
     "expr": "sum(count_over_time({namespace=\"hhccia-v2\", container=\"hhccia-core\"} |= \"generativelanguage.googleapis.com\" |= \"200 OK\" [$__auto]))"
    }
   ]
  },
  {
   "title": "Errores de acceso a Gemini + dead-letters (recientes)",
   "type": "logs",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 13 },
   "targets": [
    {
     "expr": "{namespace=\"hhccia-v2\", container=\"hhccia-core\"} |= \"generativelanguage.googleapis.com\" |~ \"HTTP/1.1 [45]\""
    },
    {
     "expr": "{namespace=\"hhccia-v2\", container=\"hhccia-core\"} |= \"dead-lettering\""
    }
   ]
  }
 ]
}
{
 "title": "HHCCIA — Registros aceptados / rechazados",
 "tags": [
  "hhccia",
  "records",
  "auditoria"
 ],
 "time": { "from": "now-30d", "to": "now" },
 "refresh": "30m",
 "templating": {
  "list": [
   {
    "name": "service",
    "label": "Servicio",
    "query": "SELECT DISTINCT coalesce(service_code,'(sin servicio)') FROM clinical_record_report ORDER BY 1"
   }
  ]
 },
 "panels": [
  {
   "title": "Aceptados (rango)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT count(*) AS value FROM clinical_record_report WHERE status IN ('approved','applied') AND $__timeFilter(reviewed_at) AND coalesce(service_code,'(sin servicio)') IN (${service:sqlstring})"
    }
   ]
  },
  {
   "title": "Rechazados (rango)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT count(*) AS value FROM clinical_record_report WHERE status = 'rejected' AND $__timeFilter(reviewed_at) AND coalesce(service_code,'(sin servicio)') IN (${service:sqlstring})"
    }
   ]
  },
  {
   "title": "Tasa de aprobación (rango)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT round(100.0 * count(*) FILTER (WHERE status IN ('approved','applied')) / NULLIF(count(*) FILTER (WHERE status IN ('approved','applied','rejected')),0), 1) AS value FROM clinical_record_report WHERE $__timeFilter(reviewed_at) AND coalesce(service_code,'(sin servicio)') IN (${service:sqlstring})"
    }
   ]
  },
  {
   "title": "Aprobados (approved)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT count(*) AS value FROM clinical_record_report WHERE status = 'approved' AND $__timeFilter(reviewed_at) AND coalesce(service_code,'(sin servicio)') IN (${service:sqlstring})"
    }
   ]
  },
  {
   "title": "Aplicados (applied)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT count(*) AS value FROM clinical_record_report WHERE status = 'applied' AND $__timeFilter(reviewed_at) AND coalesce(service_code,'(sin servicio)') IN (${service:sqlstring})"
    }
   ]
  },
  {
   "title": "Pendientes de revisión (ahora)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT count(*) AS value FROM clinical_record_report WHERE status = 'pending_review' AND coalesce(service_code,'(sin servicio)') IN (${service:sqlstring})"
    }
   ]
  },
  {
   "title": "Aceptados vs Rechazados por día (reviewed_at)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT $__timeGroup(reviewed_at,'1d') AS time, count(*) FILTER (WHERE status IN ('approved','applied')) AS \"Aceptados\", count(*) FILTER (WHERE status = 'rejected') AS \"Rechazados\" FROM clinical_record_report WHERE $__timeFilter(reviewed_at) AND status IN ('approved','applied','rejected') AND coalesce(service_code,'(sin servicio)') IN (${service:sqlstring}) GROUP BY 1 ORDER BY 1"
    }
   ]
  },
  {
   "title": "Desglose diario por estado (reviewed_at)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT $__timeGroup(reviewed_at,'1d') AS time, status AS metric, count(*) AS value FROM clinical_record_report WHERE $__timeFilter(reviewed_at) AND status IN ('approved','applied','rejected') AND coalesce(service_code,'(sin servicio)') IN (${service:sqlstring}) GROUP BY 1, status ORDER BY 1"
    }
   ]
  },
  {
   "title": "Ingresados por día por servicio (created_at)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT $__timeGroup(created_at,'1d') AS time, coalesce(service_code,'(sin servicio)') AS metric, count(*) AS value FROM clinical_record_report WHERE $__timeFilter(created_at) AND coalesce(service_code,'(sin servicio)') IN (${service:sqlstring}) GROUP BY 1, 2 ORDER BY 1"
    }
   ]
  },
  {
   "title": "Tasa de aprobación diaria %",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "rawSql": "SELECT $__timeGroup(reviewed_at,'1d') AS time, round(100.0 * count(*) FILTER (WHERE status IN ('approved','applied')) / NULLIF(count(*) FILTER (WHERE status IN ('approved','applied','rejected')),0),1) AS \"Tasa de aprobación %\" FROM clinical_record_report WHERE $__timeFilter(reviewed_at) AND status IN ('approved','applied','rejected') AND coalesce(service_code,'(sin servicio)') IN (${service:sqlstring}) GROUP BY 1 ORDER BY 1"
    }
   ]
  },
  {
   "title": "Aceptados / Rechazados por servicio (rango)",
   "type": "table",
   "gridPos": { "h": 9, "w": 14, "x": 0, "y": 30 },
   "targets": [
    {
     "rawSql": "SELECT coalesce(service_code,'(sin servicio)') AS \"Servicio\", count(*) FILTER (WHERE status IN ('approved','applied')) AS \"Aceptados\", count(*) FILTER (WHERE status = 'rejected') AS \"Rechazados\", round(100.0 * count(*) FILTER (WHERE status IN ('approved','applied')) / NULLIF(count(*) FILTER (WHERE status IN ('approved','applied','rejected')),0),1) AS \"Tasa aprob. %\" FROM clinical_record_report WHERE $__timeFilter(reviewed_at) AND status IN ('approved','applied','rejected') AND coalesce(service_code,'(sin servicio)') IN (${service:sqlstring}) GROUP BY 1 ORDER BY 2 DESC"
    }
   ]
  },
  {
   "title": "Rechazos por servicio (rango)",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 10, "x": 14, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT coalesce(service_code,'(sin servicio)') AS metric, count(*) AS value FROM clinical_record_report WHERE $__timeFilter(reviewed_at) AND status = 'rejected' AND coalesce(service_code,'(sin servicio)') IN (${service:sqlstring}) GROUP BY 1 ORDER BY 2 DESC"
    }
   ]
  },
  {
   "title": "Aceptados / Rechazados por profesional (rango)",
   "type": "table",
   "gridPos": { "h": 9, "w": 14, "x": 0, "y": 39 },
   "targets": [
    {
     "rawSql": "SELECT coalesce(professional,'(sin profesional)') AS \"Profesional\", count(*) FILTER (WHERE status IN ('approved','applied')) AS \"Aceptados\", count(*) FILTER (WHERE status = 'rejected') AS \"Rechazados\", round(100.0 * count(*) FILTER (WHERE status IN ('approved','applied')) / NULLIF(count(*) FILTER (WHERE status IN ('approved','applied','rejected')),0),1) AS \"Tasa aprob. %\" FROM clinical_record_report WHERE $__timeFilter(reviewed_at) AND status IN ('approved','applied','rejected') AND coalesce(service_code,'(sin servicio)') IN (${service:sqlstring}) GROUP BY 1 ORDER BY 3 DESC"
    }
   ]
  },
  {
   "title": "Rechazos por profesional (top 10, rango)",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 10, "x": 14, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT coalesce(professional,'(sin profesional)') AS metric, count(*) AS value FROM clinical_record_report WHERE $__timeFilter(reviewed_at) AND status = 'rejected' AND coalesce(service_code,'(sin servicio)') IN (${service:sqlstring}) GROUP BY 1 ORDER BY 2 DESC LIMIT 10"
    }
   ]
  },
  {
   "title": "Decisiones por revisor (rango)",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 48 },
   "targets": [
    {
     "rawSql": "SELECT coalesce(reviewer,'(sin revisor)') AS \"Revisor\", count(*) FILTER (WHERE status IN ('approved','applied')) AS \"Aceptados\", count(*) FILTER (WHERE status = 'rejected') AS \"Rechazados\", count(*) AS \"Total\" FROM clinical_record_report WHERE $__timeFilter(reviewed_at) AND status IN ('approved','applied','rejected') AND coalesce(service_code,'(sin servicio)') IN (${service:sqlstring}) GROUP BY 1 ORDER BY 4 DESC"
    }
   ]
  },
  {
   "title": "Pendientes de revisión por profesional (ahora)",
   "type": "table",
   "description": "Backlog actual de registros con status pending_review, agrupado por profesional. Snapshot del momento (sin filtro de tiempo), igual que el stat 'Pendientes de revisión (ahora)'.",
   "gridPos": { "h": 9, "w": 14, "x": 0, "y": 56 },
   "targets": [
    {
     "rawSql": "SELECT coalesce(professional,'(sin profesional)') AS \"Profesional\", count(*) AS \"Pendientes\" FROM clinical_record_report WHERE status = 'pending_review' AND coalesce(service_code,'(sin servicio)') IN (${service:sqlstring}) GROUP BY 1 ORDER BY 2 DESC"
    }
   ]
  },
  {
   "title": "Pendientes por profesional (top 10, ahora)",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 10, "x": 14, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT coalesce(professional,'(sin profesional)') AS metric, count(*) AS value FROM clinical_record_report WHERE status = 'pending_review' AND coalesce(service_code,'(sin servicio)') IN (${service:sqlstring}) GROUP BY 1 ORDER BY 2 DESC LIMIT 10"
    }
   ]
  }
 ]
}
{
 "title": "Authentik — Usuarios y accesos",
 "tags": [
  "authentik",
  "usuarios",
  "auth"
 ],
 "time": { "from": "now-30d", "to": "now" },
 "refresh": "30m",
 "panels": [
  {
   "title": "Usuarios activos (ahora)",
   "type": "stat",
   "description": "Cuentas humanas activas (excluye service accounts). Sin filtro de tiempo.",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT count(*) AS value FROM authentik_core_user WHERE is_active = true AND type NOT IN ('service_account','internal_service_account')"
    }
   ]
  },
  {
   "title": "Usuarios creados (rango)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT count(*) AS value FROM authentik_core_user WHERE $__timeFilter(date_joined)"
    }
   ]
  },
  {
   "title": "Logins (rango)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT count(*) AS value FROM authentik_events_event WHERE action = 'login' AND $__timeFilter(created)"
    }
   ]
  },
  {
   "title": "Usuarios que ingresaron (rango)",
   "type": "stat",
   "description": "Cantidad de usuarios distintos con al menos un login en el rango.",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT count(DISTINCT coalesce(\"user\"->>'username', context->>'username')) AS value FROM authentik_events_event WHERE action = 'login' AND $__timeFilter(created)"
    }
   ]
  },
  {
   "title": "Activos sin PRF (ahora)",
   "type": "stat",
   "description": "Usuarios humanos activos sin attributes.prf cargado — calidad de datos.",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT count(*) AS value FROM authentik_core_user WHERE is_active = true AND (attributes->>'prf') IS NULL AND type NOT IN ('service_account','internal_service_account')"
    }
   ]
  },
  {
   "title": "Logins fallidos (rango)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT count(*) AS value FROM authentik_events_event WHERE action = 'login_failed' AND $__timeFilter(created)"
    }
   ]
  },
  {
   "title": "Usuarios creados por día (date_joined)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT $__timeGroup(date_joined,'1d') AS time, count(*) AS \"Usuarios creados\" FROM authentik_core_user WHERE $__timeFilter(date_joined) GROUP BY 1 ORDER BY 1"
    }
   ]
  },
  {
   "title": "Logins por día (OK vs fallidos)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT $__timeGroup(created,'1d') AS time, count(*) FILTER (WHERE action='login') AS \"Logins OK\", count(*) FILTER (WHERE action='login_failed') AS \"Fallidos\" FROM authentik_events_event WHERE action IN ('login','login_failed') AND $__timeFilter(created) GROUP BY 1 ORDER BY 1"
    }
   ]
  },
  {
   "title": "Últimos logins (rango)",
   "type": "table",
   "description": "Eventos action='login' en el rango, más reciente primero. PRF unido desde el usuario.",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 12 },
   "targets": [
    {
     "rawSql": "SELECT e.created AS \"Fecha\", coalesce(e.\"user\"->>'username', e.context->>'username') AS \"Usuario\", u.attributes->>'prf' AS \"PRF\", u.attributes->>'service' AS \"Servicio\", e.client_ip AS \"IP\", e.app AS \"App\" FROM authentik_events_event e LEFT JOIN authentik_core_user u ON u.username = coalesce(e.\"user\"->>'username', e.context->>'username') WHERE e.action = 'login' AND $__timeFilter(e.created) ORDER BY e.created DESC LIMIT 200"
    }
   ]
  },
  {
   "title": "Listado de usuarios (todos)",
   "type": "table",
   "description": "Todas las cuentas humanas (excluye service accounts), con metadata PRF / Servicio. Sin filtro de tiempo.",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 22 },
   "targets": [
    {
     "rawSql": "SELECT u.username AS \"Usuario\", u.name AS \"Nombre\", u.email AS \"Email\", u.attributes->>'prf' AS \"PRF\", u.attributes->>'service' AS \"Servicio\", u.type AS \"Tipo\", u.is_active AS \"Activo\", u.date_joined AS \"Creado\", u.last_login AS \"Último login\" FROM authentik_core_user u WHERE u.type NOT IN ('service_account','internal_service_account') ORDER BY u.date_joined DESC"
    }
   ]
  },
  {
   "title": "Usuarios activos sin PRF",
   "type": "table",
   "description": "Calidad de datos: cuentas activas que no tienen attributes.prf cargado.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "targets": [
    {
     "rawSql": "SELECT u.username AS \"Usuario\", u.email AS \"Email\", u.date_joined AS \"Creado\", u.last_login AS \"Último login\" FROM authentik_core_user u WHERE u.is_active = true AND (u.attributes->>'prf') IS NULL AND u.type NOT IN ('service_account','internal_service_account') ORDER BY u.date_joined DESC"
    }
   ]
  },
  {
   "title": "Usuarios por servicio (attributes.service)",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
   "targets": [
    {
     "rawSql": "SELECT coalesce(u.attributes->>'service','(sin servicio)') AS \"Servicio\", count(*) AS \"Usuarios\" FROM authentik_core_user u WHERE u.type NOT IN ('service_account','internal_service_account') GROUP BY 1 ORDER BY 2 DESC"
    }
   ]
  }
 ]
}
{
 "title": "Gemini API — Costo facturado (GCP Billing)",
 "tags": [
  "gemini",
  "cost",
  "billing",
  "hhccia"
 ],
 "time": { "from": "now-30d", "to": "now" },
 "refresh": "1h",
 "panels": [
  {
   "title": "Costo neto (rango)",
   "type": "stat",
   "description": "Costo facturado por Google para el servicio 'Gemini API' en el rango seleccionado (cost + creditos).",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "location": "US",
     "project": "gen-lang-client-0005670378",
     "rawSql": "SELECT ROUND(SUM(cost) + SUM(IFNULL((SELECT SUM(c.amount) FROM UNNEST(credits) c),0)),4) AS value FROM `gen-lang-client-0005670378.all_billing_data_1.gcp_billing_export_v1_01878F_0656E4_1C5C89` WHERE service.description='Gemini API' AND $__timeFilter(usage_start_time)"
    }
   ]
  },
  {
   "title": "Costo hoy (UTC)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 5, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "location": "US",
     "project": "gen-lang-client-0005670378",
     "rawSql": "SELECT ROUND(SUM(cost) + SUM(IFNULL((SELECT SUM(c.amount) FROM UNNEST(credits) c),0)),4) AS value FROM `gen-lang-client-0005670378.all_billing_data_1.gcp_billing_export_v1_01878F_0656E4_1C5C89` WHERE service.description='Gemini API' AND usage_start_time >= TIMESTAMP_TRUNC(CURRENT_TIMESTAMP(), DAY)"
    }
   ]
  },
  {
   "title": "Mes en curso (factura)",
   "type": "stat",
   "description": "Costo del mes calendario en curso segun invoice.month (coincide con la factura de Google).",
   "gridPos": { "h": 4, "w": 5, "x": 10, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "location": "US",
     "project": "gen-lang-client-0005670378",
     "rawSql": "SELECT ROUND(SUM(cost) + SUM(IFNULL((SELECT SUM(c.amount) FROM UNNEST(credits) c),0)),4) AS value FROM `gen-lang-client-0005670378.all_billing_data_1.gcp_billing_export_v1_01878F_0656E4_1C5C89` WHERE service.description='Gemini API' AND invoice.month = FORMAT_DATE('%Y%m', CURRENT_DATE())"
    }
   ]
  },
  {
   "title": "Mes anterior (factura)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "location": "US",
     "project": "gen-lang-client-0005670378",
     "rawSql": "SELECT ROUND(SUM(cost) + SUM(IFNULL((SELECT SUM(c.amount) FROM UNNEST(credits) c),0)),4) AS value FROM `gen-lang-client-0005670378.all_billing_data_1.gcp_billing_export_v1_01878F_0656E4_1C5C89` WHERE service.description='Gemini API' AND invoice.month = FORMAT_DATE('%Y%m', DATE_SUB(CURRENT_DATE(), INTERVAL 1 MONTH))"
    }
   ]
  },
  {
   "title": "Tokens facturados (rango)",
   "type": "stat",
   "description": "Suma de usage.amount (conteo de tokens) para Gemini API en el rango.",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "location": "US",
     "project": "gen-lang-client-0005670378",
     "rawSql": "SELECT ROUND(SUM(usage.amount),0) AS value FROM `gen-lang-client-0005670378.all_billing_data_1.gcp_billing_export_v1_01878F_0656E4_1C5C89` WHERE service.description='Gemini API' AND $__timeFilter(usage_start_time)"
    }
   ]
  },
  {
   "title": "Costo diario por modelo",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "location": "US",
     "project": "gen-lang-client-0005670378",
     "rawSql": "SELECT $__timeGroup(usage_start_time,'1d') AS time, CONCAT('gemini ', REGEXP_EXTRACT(LOWER(sku.description), r'gemini[ _]?([0-9.]+ ?(?:pro|flash)(?: lite)?(?: preview)?)')) AS metric, ROUND(SUM(cost) + SUM(IFNULL((SELECT SUM(c.amount) FROM UNNEST(credits) c),0)),6) AS value FROM `gen-lang-client-0005670378.all_billing_data_1.gcp_billing_export_v1_01878F_0656E4_1C5C89` WHERE service.description='Gemini API' AND $__timeFilter(usage_start_time) GROUP BY time, metric ORDER BY time"
    }
   ]
  },
  {
   "title": "Costo diario por tipo de token (input / output / cached)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "location": "US",
     "project": "gen-lang-client-0005670378",
     "rawSql": "SELECT $__timeGroup(usage_start_time,'1d') AS time, CASE WHEN LOWER(sku.description) LIKE '%cached%' THEN 'cached input' WHEN LOWER(sku.description) LIKE '%output%' THEN 'output' WHEN LOWER(sku.description) LIKE '%input%' THEN 'input' ELSE 'other' END AS metric, ROUND(SUM(cost) + SUM(IFNULL((SELECT SUM(c.amount) FROM UNNEST(credits) c),0)),6) AS value FROM `gen-lang-client-0005670378.all_billing_data_1.gcp_billing_export_v1_01878F_0656E4_1C5C89` WHERE service.description='Gemini API' AND $__timeFilter(usage_start_time) GROUP BY time, metric ORDER BY time"
    }
   ]
  },
  {
   "title": "Costo por modelo (rango)",
   "type": "barchart",
   "description": "Costo neto por modelo en el rango. Barras (no torta) porque gemini 3.5 flash domina ~96-99% del gasto: una torta se ve igual en cualquier rango aunque los valores cambien; las barras muestran el costo absoluto y responden al filtro de fecha.",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "location": "US",
     "project": "gen-lang-client-0005670378",
     "rawSql": "SELECT CONCAT('gemini ', REGEXP_EXTRACT(LOWER(sku.description), r'gemini[ _]?([0-9.]+ ?(?:pro|flash)(?: lite)?(?: preview)?)')) AS metric, ROUND(SUM(cost) + SUM(IFNULL((SELECT SUM(c.amount) FROM UNNEST(credits) c),0)),6) AS value FROM `gen-lang-client-0005670378.all_billing_data_1.gcp_billing_export_v1_01878F_0656E4_1C5C89` WHERE service.description='Gemini API' AND $__timeFilter(usage_start_time) GROUP BY metric ORDER BY value DESC"
    }
   ]
  },
  {
   "title": "Detalle por modelo y tipo de token (rango)",
   "type": "table",
   "gridPos": { "h": 9, "w": 16, "x": 8, "y": 22 },
   "targets": [
    {
     "location": "US",
     "project": "gen-lang-client-0005670378",
     "rawSql": "SELECT CONCAT('gemini ', REGEXP_EXTRACT(LOWER(sku.description), r'gemini[ _]?([0-9.]+ ?(?:pro|flash)(?: lite)?(?: preview)?)')) AS modelo, CASE WHEN LOWER(sku.description) LIKE '%cached%' THEN 'cached input' WHEN LOWER(sku.description) LIKE '%output%' THEN 'output' WHEN LOWER(sku.description) LIKE '%input%' THEN 'input' ELSE 'other' END AS tipo, ROUND(SUM(usage.amount),0) AS tokens, ROUND(SUM(cost) + SUM(IFNULL((SELECT SUM(c.amount) FROM UNNEST(credits) c),0)),4) AS costo_usd FROM `gen-lang-client-0005670378.all_billing_data_1.gcp_billing_export_v1_01878F_0656E4_1C5C89` WHERE service.description='Gemini API' AND $__timeFilter(usage_start_time) GROUP BY modelo, tipo ORDER BY costo_usd DESC"
    }
   ]
  }
 ]
}