---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: alertmanager-incident-bearer
  namespace: observability
spec:
  encryptedData:
    bearer-token: AgAjZnqysjc234pYsxL4rZPMRNiOxPYEs2vPh37xhiTqBHsRux99jcmEnA2oELyHfv+UzaXU6JFp34U9nOMNZFvkZX4WIr1prK6+C2hfY/oEdMor77G97LxZiKNSSKH/yNflO5Y3c7Xq5BodCN5/wsuiW8g81IC0DthLrM/QKcNilOEsAn5iONmS1eLekAZAV2/nSP5NU8K4cY8nCZulTqDlXoV8VYrNwtCzaUPwUl7D8oEjn8fvwpJbyWLkfXhCBBFoRk1JvkmQGyc0/J/uFnKnsrpw4N99/sFolXdBhlm6QNbTLFxNM3wxK1KgNCFU1EmPnmegyCwZOI3KXTD5zOt8cG1bwnffmKgfjvkY+2vl0Qg9en8BMpousVpQphxeG+wDVexBWVcvVQ7MCZhorOTB+UafuzkcH4ypl7iviB80GzwEqFg8ratgw+FUOUtNiCvOEK4qwnoxPtbam8b42JDPqw3u4EybxsuKaLE8B4kUoG3CeeWqvLNGnthW7OyFxV2afk4Ut3HU0qjWTZmxHKir1r38SUaUe2F/bFR/8PIWeWZDi+EsslptEU7gFxQD5pLBY1POoqtd88F2xBf1vv/wfXkPrRtzwFej83Ae3PJYsdO3UKB4ckxHU4xBU9JCZ0CJmvKtX8yblcDvp9sjCUCZuq+vtC2M4LPgXtQ2cA/jtbep2imHsjFd8qFcLTurRn3NTnd3pq/K5TEICKWoLPZ+f8nz4iYUNyRmy47pESpLARWcWiWxdedefJxy
  template:
    metadata:
      name: alertmanager-incident-bearer
      namespace: observability
    type: Opaque
