---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: alertmanager-incident-bearer
  namespace: observability
spec:
  encryptedData:
    bearer-token: AgCIWBLrWs8NcHnu7NNuzhlbhXJ2SdVE76eNpuM3RoDOKKS+y9Uah3ZVCVyXX7pl24IDDiH/KTePpvpvVzJqDpYKBjhbVqS0CzSVach8K1QP0taArHKKTQ8szbRy7HvJCstM58VFMuQQBA1gGfkzO0HVST2+XwCukzxcR6IMfH3ZcW7tpxdJG4ZwoQED+/WdP2QBP+C07BBVIxTlXhVl6CZO3qeSG+0I/FkPmmQWLQK95jlW3byx8VuEpSVh6vPDf3r4ypw6kcPmLU9Pj7a/0+y+sZZAXLB5VK0fNBzGo6HUhthV4Vpm0J4q0pxftx1jcE7luxJ6dp2n+/kumOlCEmBDQRAuvpU3sGsRmTC+GpjzS0a2S9HoNV1CXIXmxceHMFSquEGB0qHZ+Me19GtHusW0EAla7kQx3H40GjRe5U3LiMxSXLjbWUHumtsAsSj3IAmubFmi16r0bo6sOGNNaaksin+BnT7Zm0LjBQk2bXXwr+aUWGkpefLTlp2Bokps+NogMj66SCQfXpgDs6kmxBwDtpDnFwDFBGzfDD7R0juWl9ELJl5jEK4RLuOHVVg8/3lcniH9oxdyJMomBBHNI6x3ktsB2k1VCzvUfpdSDQ6pl3Q6BW6mQlrAZdtbizEg0M7XPZ/xPnnBbwEz/Dg6aQE9uDuTTqGQQSqGF706wn1L04OIdGvPuzoHT3PiswVrV26mTaQegDy5r1+Cb99c+2aYx9LV8yse+vBWO8WS9QxmwhY8KhC9Oh0ib5tb
  template:
    metadata:
      name: alertmanager-incident-bearer
      namespace: observability
    type: Opaque
