---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: authentik-grafana-ro
  namespace: observability
spec:
  encryptedData:
    db-password: AgCHzHLuj6p/Y1N9ul1SR7a6E0hl9aGS8D3b8uhhk0OhbDJCpLFZL751CnLpLZzEmUHWU1O6E/14qhWSiB0Tf6dncABmhRAc2LbmOEy79Ezr8Rn1tiIBUQnjM456Vg8AA/aETC2MJEaZs+8O/gFmeahonly6NUMjeIhEE8Eu6i8oLEsm6DEF00NAeFHf4MYiKR9jdk8pNVoO4khE9Y2WwhlWGEjWsX91qBFuu8CwIr4A2Mfp/mqNga8ZtwfsqP57tiK6ZxvIjgcCOqUCZcRj6+VzDQguulqPo1Kl0hxvUDOr8cPj3f46wAVR+vHAAj2yD+YwPe0UnyY+ASv0tN9oUL7iWiSy846664tEI7r0gn4fQMgcrUzqRpFhrpg0SmLO8trwqtSLs4J6++WgU+BWPMmltq8WjsQx1SGbqtqcgDW3ETtS/dePCVbZpoE580sQfYwT4g7a8Plt4F3pfsrpltVV92bqfq4nY7i+wrShSQvAhRN58NLE8KFDB04YU5BefFwT4WyyUO3o967yPEBv9WGU8dGtgQln5EsEr/Nf/JCHrRhtpa7jwmmhdU5YVpRsRmDBkx0Z/SiqB72M5IbPjUHpUYXH3OnloXAyCYfrPeMBo0qdisQbo6Y4GujwRG+lFBN4JQcsPbJZ1bNUsLvuFT/kSsiTPMgw01lSzRkNwQCNO5UryePJIN61iTt3otjf0uSN6FDvvpwto/ApZZGqkQjMHuFaJoU4XHE8Uogi8rMAXvTiPD5H9b3i
  template:
    metadata:
      name: authentik-grafana-ro
      namespace: observability
