apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prometheus
spec:
  project: default
  sources:
  - repoURL: registry-1.docker.io/bitnamicharts
    chart: kube-prometheus
    targetRevision: 11.2.3
    helm:
      valueFiles:
      - $values/apps/operators/kube-prometheus/kube-prometheus-stack-values-production.yaml
  - repoURL: 'ssh://192.168.1.101:23231/nexoflow-k8s-apps'
    targetRevision: HEAD
    ref: values
  destination:
    server: 'https://kubernetes.default.svc' # Deploy to the local cluster
    namespace: 'kube-prometheus' 
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
