apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cloudflared
spec:
  project: default
  sources:
  - repoURL: https://helm.strrl.dev
    chart: cloudflare-tunnel-ingress-controller
    targetRevision: 0.0.18 
    helm:
      valueFiles:
      - $values/apps/operators/cloudflared/cloudflared-values-production.yaml
  - repoURL: 'ssh://192.168.1.101:23231/nexoflow-k8s-apps'
    targetRevision: HEAD
    ref: values
  source:
  destination:
    server: https://kubernetes.default.svc
    namespace: cloudflared
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
