---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflared-mssql-creds
  namespace: cloudflared
spec:
  encryptedData:
    credentials.json: AgAXTD4VyMb/i37d2cWWXmSTXIeYKt3Fgjdprnv/6nM1cn9HFNOIRS8Kh9O8G32KA7v/Wf5C2EdDBQkCluXPA9hEr4RIqRmb7wb5k7m7dqS9nB14aWGrtfmCJ7oBMJCys6kdkJQN+Cd8s+uHoNS8WYuK8SF+uyp53A6cuQi8l3wCX03OXp3fboGT3E8qXfhK5XlhkD6fAmY8n8nJJr81q9cADc+d75CptOcI8Ldi2ag0MUwO0QsJz5qvD/K8ucQc/1TMo1fhuQI7oTXjnq/PyEd5vHKYTXULYUTwrjm5K/lPV51/1yQ5HnnQ586oNb2G0dSyVh7VJ60g1aT2deaFyVyqlUouYcT8y2BbZfEPLRSQEZAdqOx8J4skUpxLGioAFxEpIdLKgXvoiKmX62ztkGavIgrudiEAQ9+1RceMYqhNn8qiaByii9Av/xlut/UTPhDWTtT4B1QlQHALSqZeqFZUMuiXJaiU7+QnAST9QJs8858DzGSBUF2T+yuVoFFNsHfBvpTI5o3D+rbhnL/a9zhMGvOccwpXtfJ9yeVCxTV0HlnayIFy87nldCYyUDbXTbTJYCo8CRbC3BbMHDiLkh901hN3gOWQSK/E3pjWCQMKcZkVoWXjcpirZHokHC3olWMD+3xQhxsQTPR4JF9FZqfUl6EdNcIGIs5iNgea4lVg+owYawhMyORT8vtXXOkbzLv5MGYqxpPeUmZMZBINsuM4WP/MrgShgndDvHJ8LvC2aKsNgcYlF4iRv9nIxe0+LKj+F5mhkCoNM8aoxBbicJHruubOI9GghzCHlTeUa7sL4NEIhavZrfZob2PheYM/4bMy4l3blL9NlpFiusqu4rm24vB4JarGC5iEUuh7Iz0MSjJFSQ66BlX6pzsIGI+8NvZ4M0A/PcLlZu7LWRQ5+Fvez7ZctdaEO0dh5O6Zg1hN
  template:
    metadata:
      name: cloudflared-mssql-creds
      namespace: cloudflared
