---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflared-k8s-api-creds
  namespace: cloudflared
spec:
  encryptedData:
    credentials.json: AgC8cI0If9nUJj+FGlZj1mrhTTPNwgUOnn8HIsEW5BwGBBYGfa6M0fDqOazY4FgIXNqP5S8oNkzsw86g2JI335jvSqc1LM0s4PfT/MP+0DPtYcZ2cWFdLvp6SYfZXnSs17UDfksGR1hPYeFPSpA3RoTTDnrJdolA1lM6JN89SFfMLcihsL43hFdzoSfXzR/HWTPSdFbIP+JQBgpOck1jUtNP8r3R1TKKvRQUzl41NUtosfSInd31unODrLddddxRyrwe3V8fQGQXi14eHFPs03TDAExBmEG3ExH6TvEk/MIt0srm0jU6UCGu7gCmnoFPFCI4BePA39puGkSxIEOD0Wjfi2hauJyCsj1IzU5Kp7r0pVU0uBKRTWWc35tx7/i6e1iTNykqBlfcVnUwxTdevrk0ztS/qvDfK3+OQfktGsq4xqDOqSr9Gl+VC0qN0U1PkMYFdPUs1yBmDSvaVDODGR5FfOfQdKHj8Tk/HkoGYkrY/yMgAumm608zlE3330YOBvdzw0FnD2J4UBNes8XIWgMtb7IksDa3s82gvAKs/MgZ1WR7qASKjS2HZWB3Z8mGp+pMRj1EI+8ZjeCLdi8WBkP59mSKvRdHRK21G+2KalprMSnuCyec1WGHIpbLEExjNciczd6kU3FFjSg4uGMMiIEwKzux/j5MTkFmDqww+B30MOe+4PdVsV3BG/s9sR3rSu8k3hoDLz2zCDaj4Ch3KYg73muBji+LvHh5mCyacAwnJs9av+xnWBE9jWmSfbyZHwEmtm1OMVebgePv61pBBTaAPfsSXb51gkpp1mAH+yC/mW4AUcmYNA4mTsDshmmMlYS07raLeS3GslfLCPNl0gup/WDssNNwtauD0BTzwK5xk9OBvj8DgwH0C1OccxVWHkO3sdooUttmY09pz1fkv1O9G6qD0L55Ww983mgHO9rF
  template:
    metadata:
      name: cloudflared-k8s-api-creds
      namespace: cloudflared
