apiVersion: v1
kind: Service
metadata:
  name: sftp
  namespace: sftp
  labels:
    app: sftp
spec:
  type: ClusterIP
  selector:
    app: sftp
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: http
