---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: sftp-credentials
  namespace: sftp
spec:
  encryptedData:
    SFTP_USERS: AgANCRTl3i+lZum1vz2OZMTGa97mDjz8jXgO2sTOHi9rJxhXyzKCgmy59Ik2yxE8/mgR7ju4OCtHj/xD9/8zT5yeJgWt77XroCSdA2XeiXbmcyh2Zr+MBicNcJsytaNMbuAog0/GKfYXzPL6+w5KfA/S6JIcE/vGAjp45IeDzJgomV+UyrPRgUyD9uYat+8YopEvwjWaf0dC2pNgz8X7naSNmXtCWF+bdFJIbyZKhXxBAwqi1H6zgDnOIF1dY3XQ87waNTUQy5fd2ZQP6A87Ds3EjjEnzu+X0d/Jf8zRw5zFEjnan3JTjvOTbUO/tGH5wSz1cIPzKCB0UACQfxNdIG2GRrgf4PBHzvu4Oubed5vutNOK6V+SnCZMlwzX40AiU1CNHxSJHhBYs6dPaC/PBpzMRnXb2O8nXyn39OUigOVMu9aiTSXVWt9mMV1XlZqEANhZie226j2R8nO7m/XM1uyitkgW4gGphk8ql9CTm4hpTtfrfp6PzJ82mL6h2YPKY20zGTMiC+R9RyZo7aI435KUbJxHuqqXfLzNBADr+sMnS54thBN7JoTlpvV23S1AEEnbY14fydnFZB60yz5JwdkT14DcKRtDbfw+JgPUAu2AWDToBjUUBt3MYE3GKRyHmLRsFbov5kwPoZrrPqsYw3chVo3gXkzHi3gXzdHNuqUE6uAG/Yqf8iZaYvROY6BSJMTwyR1q4PyWJZnsZNqXRsXG4PVoZ92Q8JYt/eDeEZpn5JmjjW7WA1u9SIslkDxR+lTb+yu52jQ=
  template:
    metadata:
      name: sftp-credentials
      namespace: sftp
