---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: sftp-credentials
  namespace: sftp
spec:
  encryptedData:
    UPLOAD_TOKEN: AgA1eqBO92Q9mK2kU87TksIjQWmYpc7RDwH3jqGKR7AgwNiLL7Msuc+qqBnOG65KC3FTVy7WcVOOiRg9yy8cwIsZNe34uBNwQAB+yIkS8b5i8oKvFyBr1AsH/g1KO/RXFQ0UxVefw1Ssvd7fdtEDMKuNUEOOo7tTFpqBFOWA+oGhBvgXhLcB99iB9riEMATYOs+annyuizyKmp7fBYsHmUo6WmXFWlvts1XSGhEvDtpBcjfXlW2jsJ1fCdV223L/+c+//lHZF3ICx+0gykJ//oPuAkCVAkkW7BynymsFN54hY6QJbl84MoJ1EaIhOfIujCG1oxVKW3wIER1iGdkaifDbQV/wKtRK2E7qy7+FzRrKRWU1+opt+Iv1w6N4IGfQqRL15bOYegX/rlDRKA+MFWOqOuvmSzU/I68FNvmp/V6Ro838LWJXQ/OTJsighFR5WSfxD/UF/1d6w9EfjuAcMrviBo+3WCySG7U4xE2uRfUfbz0OblYsc6VOlgy5cseFI7AAxElaSec0tkrTFlI1fNqhxaxV+n7ZQ3JsLhRwBhR1Dtmpb3hptu9pboMrNhFxDJ9ilFaH+JHD+VBUH4DZSkWoMiYiFtjX/EStKWVQa0lex2l1tiCVx7YuYajkN2cRy/qbEg2dQRU0nQYWt96buDmUkSnX1VQVUMlaHCsMtVfIPiILtVJWtoY30anylyUydp/3axqMDQoP32q/lJNnpcDh4/vHe95+seTGYBGZC6GsD0I4XBdkF9NFSfsc0w==
  template:
    metadata:
      name: sftp-credentials
      namespace: sftp
