---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: pami-downloader-secrets
  namespace: pami
spec:
  encryptedData:
    PAMI_PASSWORD: AgBGCbDdG4E/pQkOAnOLi3XX4U65D6qD3ULYu8lA2yqQnCGSxKYlEL3LtM79z/c81FHhCAbpKjCzPh7UhumjIkgSTrwxDw/eCeVU4N9a/Qlbb+xU3XZkM3RjHHI8Qtu7WyzOXy1KB2iwox8+3XuEGnHiQibBk4koMxViD3En3BTo857SAuv3NHS+Et47XqANLZr6K/LqlrKceKu0Ba4AtNIwvDE2PJdskktqYPxWnIVB6YJdIxd5x6LLpmkOLKdMoTLAHLf1qf8bf2RCz2o54md6zgO3+BUeHGNshD7jjFY+yYXMKRr7+mD4BJ68CYqhDxcE5gkdf4i63++rc6aCdQlw/sX4BM8VsRViajYkeio/AaQK/Hveyn4/ePuxSdgi1+2KcM0y+IvxZvXVfkZripvzaTo6uxYDiu7GHyHUhrnhd0cHweZALeR3syBDMCZ/vBCzWQPZ+6ziH43frLk/3ozby7Wa1WyPNsqZhTO243mY4leIC/IR2k3f4N6CGSJw+CCP4ATbXQLUfbwQL4QRHerRHhNYPPzEEuaOeC0oO+bqYoOO5EcFWB5zFz7tV59YNtCHmMIPEi26o5nSSXriz+Myp+XYmlc/mApZKebK34SGkpZG9Ur3IbSVB69JbTMrq73TVAQVW+AFxIFMEEDERT43tnrDn7ProUhMFdBc6bIGgBwJjTj/aNHTWEt6plhXZNHOGQT/wBRtjtgESeql5w==
    PAMI_USER: AgABQo/3rGgxMjzVMPm9z4uxM/KqdXZD4f29ghvtPvC4e3f22t+Xg76N2qjEwDbIzxhjt/fhUOVxXMh1j38AV7JCybSuknbh0udiI3dp63BEv6Wx/qufyai7ZZKUAX55fbacQy18intUw6taHOUXpW1OklabZri/Tfwl7rQjxiZhAN71igtULjzofvueQFcoEwLFknLGVTXRF2iXIPAYF0BnVjasydB8yNsajzkuGkd6+OIP2+vXm3r7uJbO+jCRtDOS7+ten8Btg8AatqPXrGAfCoCjp+kU7CaLUxs4/3m9akQ5M7PzCJsFuUeFklF1LcZgmKAoPWeexZoLbPqBBv7Om8i5nq4PSPkzRnBKMBHsEvESGotMq6sOqz4ZbUBYg2MzGsK+cncPhfCDnkncBur00OZacgmhi4ixQbWAuns+GEUiHsOimm6vJeojpJo8U6qqfOreKbKhQSHKX8ja96iAX++3b5mjYCPTL9bt7ApwR+zWLCKYjK08Ztu9EKMaCzsZ5X3sGu9icLvPpnICSI2yDmHd8zgEBJHar5gTSY2k3PQ/99DzE4jF5NI5ANesimwaascotq5CipoeDFoEh5Wk+1B2FB3G6GLJPqUp0q7aeSJzQdtGeTcZuc43VSo9+TonXc9yNW3tIBC/w5r5edtEB6InQkOqLmRV7o5ubo8N7vQxV1Ry5MTB5pFfbuRLli3FH/mVUwAFpYcX
  template:
    metadata:
      name: pami-downloader-secrets
      namespace: pami
