apiVersion: v1
kind: Secret
metadata:
  name: backup-creds-secret
  namespace: hhccia
type: Opaque
stringData:
  # The 'Access Key ID' from Cloudflare R2 Dashboard
  accessKeyId: faf18d82e60b01785eb974612510871a
  
  # The 'Secret Access Key' from Cloudflare R2 Dashboard
  secretAccessKey: c2ff0288f31898f6985906927107a7f9e234765be9f2a0fb8c2392bc447f9544
  
  # Optional: A generic password for K8up/Restic encryption
  # K8up requires a repository password to encrypt your files.
  repoPassword: soretillo123
