apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: atlas-operator
  namespace: argocd
spec:
  project: operators
  sources:
    - repoURL: ghcr.io/ariga/charts
      chart: atlas-operator
      targetRevision: 0.7.11 # Check for the latest version
      helm:
        releaseName: atlas-operator
        valueFiles:
          - $values/manifests/operators/atlas/atlas-values-production.yaml
    - repoURL: 'ssh://192.168.5.80:23231/nexoflow-k8s-apps'
      targetRevision: HEAD
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: default # The operator is typically installed in default or its own namespace
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true