apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: chatui
spec:
  project: default
  sources:
  - repoURL: 'ssh://192.168.1.10:23231/nexoflow-k8s-apps'
    path: apps/chatui
    targetRevision: 0.1.0
    helm:
      valueFiles:
      - $values/apps/chatui/chatui-values-production.yaml
  - repoURL: 'ssh://192.168.1.10:23231/nexoflow-k8s-apps'
    ref: values
  destination:
    server: 'https://kubernetes.default.svc' # Deploy to the local cluster
    namespace: 'chatui' 
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:  
      # This will create the 'chatui' namespace if it doesn't exist.
      - CreateNamespace=true
 