apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: nexoflow-cluster
  namespace: nexoflow  # The namespace where you want your database
spec:
  instances: 3
  primaryUpdateStrategy: unsupervised
  storage:
    size: 2Gi
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
