apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: support
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: System infrastructure and support services
  sourceRepos:
    - '*'
    - 'ssh://192.168.5.80:23231/nexoflow-k8s-apps'
  destinations:
    - namespace: '*'
      server: '*'
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: operators
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: Kubernetes Operators
  sourceRepos:
    - '*'
    - 'ssh://192.168.5.80:23231/nexoflow-k8s-apps'
  destinations:
    - namespace: '*'
      server: '*'
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: monitoring
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: Prometheus and Grafana monitoring stack
  sourceRepos:
    - '*'
    - 'ssh://192.168.5.80:23231/nexoflow-k8s-apps'
  destinations:
    - namespace: '*'
      server: '*'
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: nexoflow
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: Nexoflow applications
  sourceRepos:
    - '*'
    - 'ssh://192.168.5.80:23231/nexoflow-k8s-apps'
  destinations:
    - namespace: '*'
      server: '*'
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: waha
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: Waha applications
  sourceRepos:
    - '*'
    - 'ssh://192.168.5.80:23231/nexoflow-k8s-apps'
  destinations:
    - namespace: '*'
      server: '*'
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: hhccia
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: HHCCIA applications
  sourceRepos:
    - '*'
    - 'ssh://192.168.5.80:23231/nexoflow-k8s-apps'
  destinations:
    - namespace: '*'
      server: '*'
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: personales
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: Personal applications
  sourceRepos:
    - '*'
    - 'ssh://192.168.5.80:23231/nexoflow-k8s-apps'
  destinations:
    - namespace: '*'
      server: '*'
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
