apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: calcom
spec:
  project: default
  sources:
  - chart: calcom
    repoURL: https://pyrrha.github.io/calcom-helm
    targetRevision: 0.8.6
    helm:
      valueFiles:
      - $values/apps/cal.com/cal-values.yaml
  - repoURL: 'ssh://192.168.1.10:23231/nexoflow-k8s-apps'
    targetRevision: HEAD
    ref: values
  destination:
    server: 'https://kubernetes.default.svc' # Deploy to the local cluster
    namespace: 'calcom' 
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      # If the destination namespace does not exist, Argo CD will create it.
      - CreateNamespace=true
      # Uses server-side apply, which is a more robust way to manage Kubernetes objects.
      - ServerSideApply=true
